// =============================================
// MyEasyDocs - Mock Data
// =============================================
// Temporary mock data for development and visualization.
// Replace with real API calls when backend is ready.
// =============================================

import type { DocsFolder, DocsDocument } from './types';

// =============================================
// MOCK FOLDERS
// =============================================
export const MOCK_FOLDERS: DocsFolder[] = [
  {
    id: 'folder-1',
    user_id: 'user-1',
    parent_id: null,
    name: 'Documentos Importantes',
    path: '/Documentos Importantes',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 'folder-2',
    user_id: 'user-1',
    parent_id: null,
    name: 'Projetos',
    path: '/Projetos',
    created_at: '2024-01-10T10:00:00Z',
    updated_at: '2024-01-10T10:00:00Z',
  },
  {
    id: 'folder-3',
    user_id: 'user-1',
    parent_id: 'folder-1',
    name: 'Contratos',
    path: '/Documentos Importantes/Contratos',
    created_at: '2024-01-12T10:00:00Z',
    updated_at: '2024-01-12T10:00:00Z',
  },
];

// =============================================
// MOCK DOCUMENTS
// =============================================
export const MOCK_DOCUMENTS: DocsDocument[] = [
  // Root documents
  {
    id: 'doc-1',
    user_id: 'user-1',
    folder_id: null,
    name: 'Relatório Anual 2024.pdf',
    original_name: 'Relatório Anual 2024.pdf',
    mime_type: 'application/pdf',
    size: 2500000,
    r2_key: 'docs/user-1/doc-1.pdf',
    text_extraction_status: 'completed',
    is_favorite: true,
    created_at: '2024-01-20T14:30:00Z',
    updated_at: '2024-01-20T14:30:00Z',
  },
  {
    id: 'doc-2',
    user_id: 'user-1',
    folder_id: null,
    name: 'Apresentação Q1.pptx',
    original_name: 'Apresentação Q1.pptx',
    mime_type: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    size: 5200000,
    r2_key: 'docs/user-1/doc-2.pptx',
    text_extraction_status: 'completed',
    is_favorite: false,
    created_at: '2024-01-18T09:00:00Z',
    updated_at: '2024-01-18T09:00:00Z',
  },
  {
    id: 'doc-3',
    user_id: 'user-1',
    folder_id: null,
    name: 'Notas de Reunião.md',
    original_name: 'Notas de Reunião.md',
    mime_type: 'text/markdown',
    size: 15000,
    r2_key: 'docs/user-1/doc-3.md',
    text_extraction_status: 'completed',
    is_favorite: false,
    created_at: '2024-01-22T16:45:00Z',
    updated_at: '2024-01-22T16:45:00Z',
  },
  {
    id: 'doc-4',
    user_id: 'user-1',
    folder_id: null,
    name: 'Logo Empresa.png',
    original_name: 'Logo Empresa.png',
    mime_type: 'image/png',
    size: 450000,
    r2_key: 'docs/user-1/doc-4.png',
    text_extraction_status: 'unsupported',
    is_favorite: true,
    created_at: '2024-01-05T11:20:00Z',
    updated_at: '2024-01-05T11:20:00Z',
  },
  // Documents in "Documentos Importantes" folder
  {
    id: 'doc-5',
    user_id: 'user-1',
    folder_id: 'folder-1',
    name: 'Plano Estratégico.docx',
    original_name: 'Plano Estratégico.docx',
    mime_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    size: 1800000,
    r2_key: 'docs/user-1/doc-5.docx',
    text_extraction_status: 'completed',
    is_favorite: false,
    created_at: '2024-01-16T10:00:00Z',
    updated_at: '2024-01-16T10:00:00Z',
  },
  {
    id: 'doc-6',
    user_id: 'user-1',
    folder_id: 'folder-1',
    name: 'Orçamento 2024.xlsx',
    original_name: 'Orçamento 2024.xlsx',
    mime_type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size: 980000,
    r2_key: 'docs/user-1/doc-6.xlsx',
    text_extraction_status: 'completed',
    is_favorite: true,
    created_at: '2024-01-17T14:00:00Z',
    updated_at: '2024-01-17T14:00:00Z',
  },
  // Documents in "Contratos" subfolder
  {
    id: 'doc-7',
    user_id: 'user-1',
    folder_id: 'folder-3',
    name: 'Contrato Fornecedor A.pdf',
    original_name: 'Contrato Fornecedor A.pdf',
    mime_type: 'application/pdf',
    size: 1200000,
    r2_key: 'docs/user-1/doc-7.pdf',
    text_extraction_status: 'completed',
    is_favorite: false,
    created_at: '2024-01-13T09:00:00Z',
    updated_at: '2024-01-13T09:00:00Z',
  },
  {
    id: 'doc-8',
    user_id: 'user-1',
    folder_id: 'folder-3',
    name: 'Contrato Prestação Serviços.pdf',
    original_name: 'Contrato Prestação Serviços.pdf',
    mime_type: 'application/pdf',
    size: 890000,
    r2_key: 'docs/user-1/doc-8.pdf',
    text_extraction_status: 'completed',
    is_favorite: false,
    created_at: '2024-01-14T11:30:00Z',
    updated_at: '2024-01-14T11:30:00Z',
  },
  {
    id: 'doc-9',
    user_id: 'user-1',
    folder_id: 'folder-3',
    name: 'Termo de Confidencialidade.pdf',
    original_name: 'Termo de Confidencialidade.pdf',
    mime_type: 'application/pdf',
    size: 320000,
    r2_key: 'docs/user-1/doc-9.pdf',
    text_extraction_status: 'completed',
    is_favorite: false,
    created_at: '2024-01-14T15:00:00Z',
    updated_at: '2024-01-14T15:00:00Z',
  },
  // Documents in "Projetos" folder
  {
    id: 'doc-10',
    user_id: 'user-1',
    folder_id: 'folder-2',
    name: 'Projeto Alpha - Especificações.pdf',
    original_name: 'Projeto Alpha - Especificações.pdf',
    mime_type: 'application/pdf',
    size: 3400000,
    r2_key: 'docs/user-1/doc-10.pdf',
    text_extraction_status: 'completed',
    is_favorite: true,
    created_at: '2024-01-11T08:00:00Z',
    updated_at: '2024-01-11T08:00:00Z',
  },
  {
    id: 'doc-11',
    user_id: 'user-1',
    folder_id: 'folder-2',
    name: 'Cronograma Projeto Beta.xlsx',
    original_name: 'Cronograma Projeto Beta.xlsx',
    mime_type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size: 650000,
    r2_key: 'docs/user-1/doc-11.xlsx',
    text_extraction_status: 'completed',
    is_favorite: false,
    created_at: '2024-01-12T10:30:00Z',
    updated_at: '2024-01-12T10:30:00Z',
  },
];
