/**
 * Demo Profiles
 *
 * Sample user profiles for testing and development.
 */

import type { UserPersonalInfo } from '../types';

/**
 * Demo profiles for development testing
 * Note: diasTreinoSemana, tempoTreinoMinutos, and numeroRefeicoes are set to 0
 * to prevent auto-generation of workouts/diets - allowing AI chat generation testing
 */
export const DEMO_PROFILES: UserPersonalInfo[] = [
  {
    nome: 'João Silva',
    idade: 35,
    sexo: 'masculino',
    genero: 'homem-cis',
    generoOutro: '',
    peso: 95,
    altura: 178,
    objetivo: 'perder gordura e melhorar condicionamento',
    nivelAtividade: 'sedentario',
    restricoesMedicas: ['hipertensão leve'],
    lesoes: [],
    diasTreinoSemana: 0,
    tempoTreinoMinutos: 0,
    preferenciaTreino: '',
    experienciaTreino: '',
    localTreino: '',
    modalidade: '',
    restricoesAlimentares: [],
    comidasFavoritas: ['frango', 'arroz', 'feijão'],
    comidasEvitar: ['frituras'],
    numeroRefeicoes: 0,
    horarioTreino: '',
  },
  {
    nome: 'Maria Santos',
    idade: 28,
    sexo: 'masculino',
    genero: 'mulher-trans',
    generoOutro: '',
    peso: 62,
    altura: 165,
    objetivo: 'ganhar massa muscular e definição',
    nivelAtividade: 'moderado',
    restricoesMedicas: [],
    lesoes: ['dor lombar leve'],
    diasTreinoSemana: 0,
    tempoTreinoMinutos: 0,
    preferenciaTreino: '',
    experienciaTreino: '',
    localTreino: '',
    modalidade: '',
    restricoesAlimentares: ['lactose'],
    comidasFavoritas: ['ovos', 'batata doce', 'banana'],
    comidasEvitar: ['laticínios', 'peixe'],
    numeroRefeicoes: 0,
    horarioTreino: '',
  },
  {
    nome: 'Carlos Oliveira',
    idade: 32,
    sexo: 'feminino',
    genero: 'homem-trans',
    generoOutro: '',
    peso: 82,
    altura: 180,
    objetivo: 'melhorar performance e resistência',
    nivelAtividade: 'intenso',
    restricoesMedicas: [],
    lesoes: ['tendinite no ombro direito'],
    diasTreinoSemana: 0,
    tempoTreinoMinutos: 0,
    preferenciaTreino: '',
    experienciaTreino: '',
    localTreino: '',
    modalidade: '',
    restricoesAlimentares: [],
    comidasFavoritas: ['carne vermelha', 'arroz integral', 'abacate'],
    comidasEvitar: ['açúcar refinado', 'refrigerante'],
    numeroRefeicoes: 0,
    horarioTreino: '',
  },
  {
    nome: 'Ana Costa',
    idade: 42,
    sexo: 'feminino',
    genero: 'mulher-cis',
    generoOutro: '',
    peso: 68,
    altura: 160,
    objetivo: 'manter a forma e saúde geral',
    nivelAtividade: 'leve',
    restricoesMedicas: ['diabetes tipo 2'],
    lesoes: ['problema no joelho esquerdo'],
    diasTreinoSemana: 0,
    tempoTreinoMinutos: 0,
    preferenciaTreino: '',
    experienciaTreino: '',
    localTreino: '',
    modalidade: '',
    restricoesAlimentares: ['glúten', 'açúcar'],
    comidasFavoritas: ['saladas', 'legumes', 'frango'],
    comidasEvitar: ['massas', 'pães', 'doces'],
    numeroRefeicoes: 0,
    horarioTreino: '',
  },
  {
    nome: 'Fernanda Lima',
    idade: 25,
    sexo: 'feminino',
    genero: 'prefiro-nao-declarar',
    generoOutro: '',
    peso: 58,
    altura: 168,
    objetivo: 'ganhar condicionamento físico e flexibilidade',
    nivelAtividade: 'moderado',
    restricoesMedicas: [],
    lesoes: [],
    diasTreinoSemana: 0,
    tempoTreinoMinutos: 0,
    preferenciaTreino: '',
    experienciaTreino: '',
    localTreino: '',
    modalidade: '',
    restricoesAlimentares: ['vegetariano'],
    comidasFavoritas: ['tofu', 'quinoa', 'legumes'],
    comidasEvitar: ['carne', 'frango', 'peixe'],
    numeroRefeicoes: 0,
    horarioTreino: '',
  },
];
