/**
 * Exercise Database
 *
 * Complete database of exercises with detailed muscle groups,
 * movement descriptions, and external image URLs.
 */

/**
 * Exercise information interface
 */
export interface ExerciseInfo {
  id: string;
  nome: string;
  nomeIngles: string;
  descricaoMovimento: string[];
  gruposMusculares: {
    principal: string[];
    secundario: string[];
  };
  imagemMovimento: string;  // Image showing how to perform the exercise
  imagemMusculos: string;   // Image showing highlighted muscles worked
  dicas: string[];
  equipamento: string[];
  nivel: 'iniciante' | 'intermediario' | 'avancado';
  modalidade: string[];
  categoria: 'peito' | 'costas' | 'ombros' | 'biceps' | 'triceps' | 'pernas' | 'core' | 'cardio' | 'calistenia';
}

/**
 * Muscle group categories for filtering
 */
export const MUSCLE_GROUP_CATEGORIES = {
  peito: {
    nome: 'Peito',
    icon: '💪',
    subgrupos: [
      'Peitoral maior - porção clavicular (superior)',
      'Peitoral maior - porção esternal (médio)',
      'Peitoral maior - porção abdominal (inferior)',
      'Peitoral menor',
    ],
  },
  costas: {
    nome: 'Costas',
    icon: '🔙',
    subgrupos: [
      'Latíssimo do dorso',
      'Trapézio superior',
      'Trapézio médio',
      'Trapézio inferior',
      'Romboides',
      'Eretor da espinha',
      'Infraespinhal',
      'Redondo maior',
      'Redondo menor',
    ],
  },
  ombros: {
    nome: 'Ombros',
    icon: '🎯',
    subgrupos: [
      'Deltóide anterior',
      'Deltóide lateral (médio)',
      'Deltóide posterior',
      'Manguito rotador',
    ],
  },
  biceps: {
    nome: 'Bíceps',
    icon: '💪',
    subgrupos: [
      'Bíceps braquial - cabeça longa',
      'Bíceps braquial - cabeça curta',
      'Braquial',
      'Braquiorradial',
    ],
  },
  triceps: {
    nome: 'Tríceps',
    icon: '💪',
    subgrupos: [
      'Tríceps braquial - cabeça longa',
      'Tríceps braquial - cabeça lateral',
      'Tríceps braquial - cabeça medial',
    ],
  },
  pernas: {
    nome: 'Pernas',
    icon: '🦵',
    subgrupos: [
      'Quadríceps - reto femoral',
      'Quadríceps - vasto lateral',
      'Quadríceps - vasto medial',
      'Quadríceps - vasto intermédio',
      'Isquiotibiais - bíceps femoral',
      'Isquiotibiais - semitendíneo',
      'Isquiotibiais - semimembranáceo',
      'Glúteo máximo',
      'Glúteo médio',
      'Glúteo mínimo',
      'Adutores',
      'Abdutores',
      'Gastrocnêmio (panturrilha)',
      'Sóleo',
    ],
  },
  core: {
    nome: 'Core',
    icon: '🎯',
    subgrupos: [
      'Reto abdominal',
      'Oblíquos externos',
      'Oblíquos internos',
      'Transverso do abdômen',
      'Quadrado lombar',
      'Psoas ilíaco',
    ],
  },
};

/**
 * Complete exercise database
 */
export const EXERCISE_DATABASE: ExerciseInfo[] = [
  // ============ PEITO (8 exercícios) ============
  {
    id: 'supino-reto',
    nome: 'Supino Reto',
    nomeIngles: 'Flat Bench Press',
    descricaoMovimento: [
      'Deite no banco com os pés firmes no chão',
      'Segure a barra com pegada um pouco mais larga que os ombros',
      'Desça a barra controladamente até tocar levemente o peito',
      'Empurre a barra para cima até estender os braços (sem travar os cotovelos)',
      'Mantenha as escápulas retraídas durante todo o movimento',
    ],
    gruposMusculares: {
      principal: ['Peitoral maior - porção esternal (médio)'],
      secundario: ['Deltóide anterior', 'Tríceps braquial - cabeça lateral', 'Peitoral maior - porção clavicular (superior)'],
    },
    imagemMovimento: '/exercises/supino-reto.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-chest-front.png',
    dicas: [
      'Mantenha os cotovelos em ângulo de 45-75 graus em relação ao corpo',
      'Aperte os glúteos para maior estabilidade',
      'Não deixe a barra quicar no peito',
    ],
    equipamento: ['Barra', 'Banco reto', 'Anilhas'],
    nivel: 'intermediario',
    modalidade: ['musculacao'],
    categoria: 'peito',
  },
  {
    id: 'supino-inclinado',
    nome: 'Supino Inclinado',
    nomeIngles: 'Incline Bench Press',
    descricaoMovimento: [
      'Ajuste o banco em ângulo de 30-45 graus',
      'Deite com os pés firmes no chão',
      'Segure a barra com pegada um pouco mais larga que os ombros',
      'Desça a barra até a parte superior do peito',
      'Empurre para cima mantendo o controle',
    ],
    gruposMusculares: {
      principal: ['Peitoral maior - porção clavicular (superior)'],
      secundario: ['Deltóide anterior', 'Tríceps braquial', 'Peitoral maior - porção esternal (médio)'],
    },
    imagemMovimento: '/exercises/supino-inclinado.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-chest-front.png',
    dicas: [
      'Ângulos maiores focam mais nos deltoides',
      'Não arqueie excessivamente a lombar',
      'Mantenha os cotovelos levemente à frente da barra',
    ],
    equipamento: ['Barra', 'Banco inclinado', 'Anilhas'],
    nivel: 'intermediario',
    modalidade: ['musculacao'],
    categoria: 'peito',
  },
  {
    id: 'supino-declinado',
    nome: 'Supino Declinado',
    nomeIngles: 'Decline Bench Press',
    descricaoMovimento: [
      'Ajuste o banco em ângulo negativo (15-30 graus)',
      'Prenda os pés nos apoios',
      'Segure a barra com pegada um pouco mais larga que os ombros',
      'Desça a barra até a parte inferior do peito',
      'Empurre para cima com controle',
    ],
    gruposMusculares: {
      principal: ['Peitoral maior - porção abdominal (inferior)'],
      secundario: ['Tríceps braquial', 'Deltóide anterior'],
    },
    imagemMovimento: '/exercises/supino-declinado.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-chest-front.png',
    dicas: [
      'Ideal para focar na parte inferior do peitoral',
      'Use menos carga que o supino reto',
      'Tenha um parceiro para segurança',
    ],
    equipamento: ['Barra', 'Banco declinado', 'Anilhas'],
    nivel: 'intermediario',
    modalidade: ['musculacao'],
    categoria: 'peito',
  },
  {
    id: 'crucifixo',
    nome: 'Crucifixo com Halteres',
    nomeIngles: 'Dumbbell Fly',
    descricaoMovimento: [
      'Deite no banco reto segurando os halteres acima do peito',
      'Com os cotovelos levemente flexionados, abra os braços em arco',
      'Desça até sentir alongamento no peitoral',
      'Retorne ao topo contraindo o peitoral (movimento de abraço)',
      'Mantenha a mesma flexão do cotovelo durante todo o movimento',
    ],
    gruposMusculares: {
      principal: ['Peitoral maior - porção esternal (médio)', 'Peitoral maior - porção clavicular (superior)'],
      secundario: ['Deltóide anterior', 'Bíceps braquial - cabeça curta'],
    },
    imagemMovimento: '/exercises/crucifixo.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-chest-front.png',
    dicas: [
      'Não desça demais para evitar lesão no ombro',
      'Foque na contração do peitoral, não na força dos braços',
      'Use cargas moderadas para manter a técnica',
    ],
    equipamento: ['Halteres', 'Banco reto'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'peito',
  },
  {
    id: 'flexao',
    nome: 'Flexão de Braço',
    nomeIngles: 'Push-up',
    descricaoMovimento: [
      'Posicione as mãos no chão, um pouco mais largas que os ombros',
      'Mantenha o corpo reto, da cabeça aos pés',
      'Desça o corpo até o peito quase tocar o chão',
      'Empurre para cima até estender os braços',
      'Mantenha o core contraído durante todo o movimento',
    ],
    gruposMusculares: {
      principal: ['Peitoral maior - porção esternal (médio)'],
      secundario: ['Deltóide anterior', 'Tríceps braquial', 'Core (estabilização)'],
    },
    imagemMovimento: '/exercises/flexao.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-chest-front.png',
    dicas: [
      'Não deixe o quadril subir ou descer',
      'Olhe levemente à frente, não para baixo',
      'Iniciantes podem fazer com joelhos apoiados',
    ],
    equipamento: ['Nenhum (peso corporal)'],
    nivel: 'iniciante',
    modalidade: ['musculacao', 'calistenia', 'funcional'],
    categoria: 'peito',
  },
  {
    id: 'crossover',
    nome: 'Crossover no Cabo',
    nomeIngles: 'Cable Crossover',
    descricaoMovimento: [
      'Posicione-se entre duas polias altas',
      'Segure as manoplas e dê um passo à frente',
      'Com os cotovelos levemente flexionados, traga as mãos juntas à frente',
      'Cruze levemente as mãos na posição final',
      'Retorne controladamente à posição inicial',
    ],
    gruposMusculares: {
      principal: ['Peitoral maior - porção esternal (médio)', 'Peitoral maior - porção abdominal (inferior)'],
      secundario: ['Deltóide anterior', 'Bíceps braquial'],
    },
    imagemMovimento: '/exercises/crossover.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-chest-front.png',
    dicas: [
      'Mantenha uma leve inclinação do tronco para frente',
      'Foque na contração do peitoral',
      'Controle a fase excêntrica (volta)',
    ],
    equipamento: ['Crossover (polia dupla)'],
    nivel: 'intermediario',
    modalidade: ['musculacao'],
    categoria: 'peito',
  },
  {
    id: 'peck-deck',
    nome: 'Peck Deck (Voador)',
    nomeIngles: 'Pec Deck Machine',
    descricaoMovimento: [
      'Sente na máquina com as costas apoiadas',
      'Posicione os antebraços nos apoios (ou segure as manoplas)',
      'Traga os braços juntos à frente, contraindo o peitoral',
      'Retorne controladamente até sentir alongamento',
      'Não deixe o peso bater entre as repetições',
    ],
    gruposMusculares: {
      principal: ['Peitoral maior - porção esternal (médio)'],
      secundario: ['Peitoral maior - porção clavicular (superior)', 'Deltóide anterior'],
    },
    imagemMovimento: '/exercises/peck-deck.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-chest-front.png',
    dicas: [
      'Ajuste o banco para que os braços fiquem paralelos ao chão',
      'Mantenha os ombros para baixo e para trás',
      'Ótimo exercício para finalização do treino',
    ],
    equipamento: ['Máquina Peck Deck'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'peito',
  },
  {
    id: 'flexao-inclinada',
    nome: 'Flexão Inclinada (Pés Elevados)',
    nomeIngles: 'Decline Push-up',
    descricaoMovimento: [
      'Apoie os pés em uma superfície elevada (banco, caixa)',
      'Posicione as mãos no chão, um pouco mais largas que os ombros',
      'Mantenha o corpo reto',
      'Desça o peito em direção ao chão',
      'Empurre para cima até estender os braços',
    ],
    gruposMusculares: {
      principal: ['Peitoral maior - porção clavicular (superior)'],
      secundario: ['Deltóide anterior', 'Tríceps braquial', 'Core'],
    },
    imagemMovimento: '/exercises/flexao-inclinada.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-chest-front.png',
    dicas: [
      'Quanto mais alto os pés, maior o foco no peitoral superior',
      'Mantenha o core bem contraído',
      'Boa progressão para flexões avançadas',
    ],
    equipamento: ['Banco ou caixa'],
    nivel: 'intermediario',
    modalidade: ['calistenia', 'funcional'],
    categoria: 'peito',
  },

  // ============ COSTAS (10 exercícios) ============
  {
    id: 'puxada-frontal',
    nome: 'Puxada Frontal',
    nomeIngles: 'Lat Pulldown',
    descricaoMovimento: [
      'Sente no banco e prenda as coxas sob os apoios',
      'Segure a barra com pegada pronada (palmas para frente), mais larga que os ombros',
      'Puxe a barra até a altura do peito, trazendo os cotovelos para baixo e para trás',
      'Retorne controladamente até os braços estenderem completamente',
      'Mantenha o tronco levemente inclinado para trás',
    ],
    gruposMusculares: {
      principal: ['Latíssimo do dorso'],
      secundario: ['Redondo maior', 'Bíceps braquial', 'Romboides', 'Trapézio inferior'],
    },
    imagemMovimento: '/exercises/puxada-frontal.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-lats-back.png',
    dicas: [
      'Não balance o tronco para puxar o peso',
      'Concentre-se em "puxar com os cotovelos"',
      'Evite encolher os ombros',
    ],
    equipamento: ['Máquina de puxada', 'Barra reta'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'costas',
  },
  {
    id: 'remada-curvada',
    nome: 'Remada Curvada com Barra',
    nomeIngles: 'Bent Over Barbell Row',
    descricaoMovimento: [
      'Segure a barra com pegada pronada, largura dos ombros',
      'Incline o tronco a aproximadamente 45 graus, joelhos levemente flexionados',
      'Mantenha as costas retas e o core contraído',
      'Puxe a barra em direção ao abdômen',
      'Desça controladamente até os braços estenderem',
    ],
    gruposMusculares: {
      principal: ['Latíssimo do dorso', 'Romboides'],
      secundario: ['Trapézio médio', 'Bíceps braquial', 'Eretor da espinha', 'Deltóide posterior'],
    },
    imagemMovimento: '/exercises/remada-curvada.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-lats-back.png',
    dicas: [
      'Não arredonde as costas',
      'Mantenha o pescoço neutro',
      'Aperte as escápulas no topo do movimento',
    ],
    equipamento: ['Barra', 'Anilhas'],
    nivel: 'intermediario',
    modalidade: ['musculacao'],
    categoria: 'costas',
  },
  {
    id: 'remada-baixa',
    nome: 'Remada Baixa no Cabo',
    nomeIngles: 'Seated Cable Row',
    descricaoMovimento: [
      'Sente com os pés apoiados na plataforma, joelhos levemente flexionados',
      'Segure a manopla com as duas mãos',
      'Mantenha as costas retas e o peito para fora',
      'Puxe a manopla em direção ao abdômen',
      'Retorne controladamente, estendendo os braços completamente',
    ],
    gruposMusculares: {
      principal: ['Latíssimo do dorso', 'Romboides'],
      secundario: ['Trapézio médio', 'Bíceps braquial', 'Eretor da espinha'],
    },
    imagemMovimento: '/exercises/remada-baixa.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-lats-back.png',
    dicas: [
      'Não incline o tronco para trás para puxar o peso',
      'Contraia as escápulas no final do movimento',
      'Mantenha os ombros baixos',
    ],
    equipamento: ['Máquina de cabo', 'Manopla triangular'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'costas',
  },
  {
    id: 'levantamento-terra',
    nome: 'Levantamento Terra',
    nomeIngles: 'Deadlift',
    descricaoMovimento: [
      'Posicione os pés na largura dos quadris, barra sobre o meio dos pés',
      'Agache e segure a barra com pegada mista ou pronada',
      'Mantenha as costas retas, peito para fora, olhar para frente',
      'Levante a barra estendendo quadris e joelhos simultaneamente',
      'No topo, contraia os glúteos sem hiperestender a lombar',
      'Desça controladamente, empurrando o quadril para trás',
    ],
    gruposMusculares: {
      principal: ['Eretor da espinha', 'Glúteo máximo', 'Isquiotibiais'],
      secundario: ['Latíssimo do dorso', 'Trapézio', 'Quadríceps', 'Core', 'Antebraços'],
    },
    imagemMovimento: '/exercises/levantamento-terra.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-lower-back-back.png',
    dicas: [
      'A barra deve subir rente às pernas',
      'Não arredonde as costas em nenhum momento',
      'Comece com cargas leves para aprender a técnica',
    ],
    equipamento: ['Barra', 'Anilhas'],
    nivel: 'avancado',
    modalidade: ['musculacao'],
    categoria: 'costas',
  },
  {
    id: 'barra-fixa',
    nome: 'Barra Fixa (Pull-up)',
    nomeIngles: 'Pull-up',
    descricaoMovimento: [
      'Segure a barra com pegada pronada, um pouco mais larga que os ombros',
      'Inicie pendurado com os braços estendidos',
      'Puxe o corpo para cima até o queixo passar a barra',
      'Desça controladamente até estender completamente os braços',
      'Mantenha o core contraído durante todo o movimento',
    ],
    gruposMusculares: {
      principal: ['Latíssimo do dorso'],
      secundario: ['Bíceps braquial', 'Redondo maior', 'Romboides', 'Trapézio inferior', 'Core'],
    },
    imagemMovimento: '/exercises/barra-fixa.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-lats-back.png',
    dicas: [
      'Evite balançar o corpo',
      'Inicie o movimento puxando as escápulas para baixo',
      'Iniciantes podem usar elástico de assistência',
    ],
    equipamento: ['Barra fixa'],
    nivel: 'intermediario',
    modalidade: ['musculacao', 'calistenia'],
    categoria: 'costas',
  },
  {
    id: 'remada-unilateral',
    nome: 'Remada Unilateral com Halter',
    nomeIngles: 'Single Arm Dumbbell Row',
    descricaoMovimento: [
      'Apoie um joelho e uma mão no banco',
      'Segure o halter com a mão livre, braço estendido',
      'Mantenha as costas paralelas ao chão',
      'Puxe o halter em direção ao quadril',
      'Desça controladamente até estender o braço',
    ],
    gruposMusculares: {
      principal: ['Latíssimo do dorso'],
      secundario: ['Romboides', 'Trapézio médio', 'Bíceps braquial', 'Deltóide posterior'],
    },
    imagemMovimento: '/exercises/remada-unilateral.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-lats-back.png',
    dicas: [
      'Não gire o tronco para levantar o peso',
      'Mantenha o cotovelo próximo ao corpo',
      'Foque em puxar com o cotovelo, não com a mão',
    ],
    equipamento: ['Halter', 'Banco'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'costas',
  },
  {
    id: 'pullover',
    nome: 'Pullover com Halter',
    nomeIngles: 'Dumbbell Pullover',
    descricaoMovimento: [
      'Deite transversalmente no banco, apoiando apenas a parte superior das costas',
      'Segure o halter com as duas mãos acima do peito',
      'Com os braços levemente flexionados, leve o halter para trás da cabeça',
      'Desça até sentir alongamento no peitoral e dorsal',
      'Retorne à posição inicial contraindo o dorsal',
    ],
    gruposMusculares: {
      principal: ['Latíssimo do dorso', 'Peitoral maior'],
      secundario: ['Tríceps braquial - cabeça longa', 'Redondo maior', 'Serrátil anterior'],
    },
    imagemMovimento: '/exercises/pullover.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-lats-back.png',
    dicas: [
      'Mantenha os quadris baixos durante o movimento',
      'Não flexione demais os cotovelos',
      'Movimento excelente para expansão torácica',
    ],
    equipamento: ['Halter', 'Banco'],
    nivel: 'intermediario',
    modalidade: ['musculacao'],
    categoria: 'costas',
  },
  {
    id: 'remada-cavalinho',
    nome: 'Remada Cavalinho (T-Bar Row)',
    nomeIngles: 'T-Bar Row',
    descricaoMovimento: [
      'Posicione-se sobre a barra fixa no chão ou máquina T-Bar',
      'Incline o tronco a aproximadamente 45 graus',
      'Segure a manopla com as duas mãos',
      'Puxe o peso em direção ao peito/abdômen',
      'Desça controladamente até estender os braços',
    ],
    gruposMusculares: {
      principal: ['Latíssimo do dorso', 'Romboides', 'Trapézio médio'],
      secundario: ['Bíceps braquial', 'Eretor da espinha', 'Deltóide posterior'],
    },
    imagemMovimento: '/exercises/remada-cavalinho.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-lats-back.png',
    dicas: [
      'Mantenha as costas retas',
      'Aperte as escápulas no topo',
      'Não use impulso para levantar o peso',
    ],
    equipamento: ['Barra T-Bar ou Landmine'],
    nivel: 'intermediario',
    modalidade: ['musculacao'],
    categoria: 'costas',
  },
  {
    id: 'face-pull',
    nome: 'Face Pull',
    nomeIngles: 'Face Pull',
    descricaoMovimento: [
      'Ajuste a polia na altura do rosto',
      'Segure a corda com pegada neutra',
      'Puxe a corda em direção ao rosto, separando as mãos',
      'Os cotovelos devem ficar altos e abertos',
      'Retorne controladamente à posição inicial',
    ],
    gruposMusculares: {
      principal: ['Deltóide posterior', 'Trapézio médio', 'Romboides'],
      secundario: ['Infraespinhal', 'Redondo menor', 'Bíceps braquial'],
    },
    imagemMovimento: '/exercises/face-pull.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-rear-delts-back.png',
    dicas: [
      'Excelente para saúde do ombro',
      'Mantenha os cotovelos acima dos punhos',
      'Foque na rotação externa no final',
    ],
    equipamento: ['Polia', 'Corda'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'costas',
  },
  {
    id: 'hiperextensao',
    nome: 'Hiperextensão Lombar',
    nomeIngles: 'Back Extension',
    descricaoMovimento: [
      'Posicione-se no aparelho com os quadris apoiados na almofada',
      'Prenda os pés nos apoios',
      'Cruze os braços no peito ou atrás da cabeça',
      'Desça o tronco até aproximadamente 90 graus',
      'Suba contraindo os eretores da espinha e glúteos',
    ],
    gruposMusculares: {
      principal: ['Eretor da espinha'],
      secundario: ['Glúteo máximo', 'Isquiotibiais'],
    },
    imagemMovimento: '/exercises/hiperextensao.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-lower-back-back.png',
    dicas: [
      'Não hiperestenda a lombar no topo',
      'Movimento lento e controlado',
      'Pode adicionar peso conforme evolução',
    ],
    equipamento: ['Aparelho de hiperextensão'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'costas',
  },

  // ============ OMBROS (8 exercícios) ============
  {
    id: 'desenvolvimento',
    nome: 'Desenvolvimento com Barra',
    nomeIngles: 'Overhead Press',
    descricaoMovimento: [
      'Segure a barra na altura dos ombros, pegada um pouco mais larga que os ombros',
      'Pés na largura dos quadris, core contraído',
      'Empurre a barra para cima até estender os braços',
      'Mova a cabeça levemente para frente quando a barra passar',
      'Desça controladamente até a posição inicial',
    ],
    gruposMusculares: {
      principal: ['Deltóide anterior', 'Deltóide lateral (médio)'],
      secundario: ['Tríceps braquial', 'Trapézio superior', 'Core (estabilização)'],
    },
    imagemMovimento: '/exercises/desenvolvimento.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-shoulders-front.png',
    dicas: [
      'Não arqueie a lombar excessivamente',
      'Mantenha os cotovelos levemente à frente da barra',
      'Pode ser feito sentado para maior isolamento',
    ],
    equipamento: ['Barra', 'Anilhas'],
    nivel: 'intermediario',
    modalidade: ['musculacao'],
    categoria: 'ombros',
  },
  {
    id: 'elevacao-lateral',
    nome: 'Elevação Lateral',
    nomeIngles: 'Lateral Raise',
    descricaoMovimento: [
      'Em pé, segure os halteres ao lado do corpo',
      'Com os cotovelos levemente flexionados, eleve os braços lateralmente',
      'Suba até a altura dos ombros (formando um T)',
      'Desça controladamente',
      'Mantenha os punhos neutros ou levemente inclinados para baixo',
    ],
    gruposMusculares: {
      principal: ['Deltóide lateral (médio)'],
      secundario: ['Deltóide anterior', 'Trapézio superior'],
    },
    imagemMovimento: '/exercises/elevacao-lateral.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-shoulders-front.png',
    dicas: [
      'Não use impulso do corpo',
      'Incline levemente os punhos como se estivesse derramando água',
      'Use cargas moderadas para manter a técnica',
    ],
    equipamento: ['Halteres'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'ombros',
  },
  {
    id: 'elevacao-frontal',
    nome: 'Elevação Frontal',
    nomeIngles: 'Front Raise',
    descricaoMovimento: [
      'Em pé, segure os halteres à frente das coxas',
      'Com os cotovelos levemente flexionados, eleve os braços à frente',
      'Suba até a altura dos ombros',
      'Desça controladamente',
      'Pode alternar os braços ou fazer simultâneo',
    ],
    gruposMusculares: {
      principal: ['Deltóide anterior'],
      secundario: ['Peitoral maior - porção clavicular (superior)', 'Trapézio superior'],
    },
    imagemMovimento: '/exercises/elevacao-frontal.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-shoulders-front.png',
    dicas: [
      'Não balance o tronco',
      'Mantenha o core contraído',
      'Não suba além da linha dos ombros',
    ],
    equipamento: ['Halteres'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'ombros',
  },
  {
    id: 'elevacao-posterior',
    nome: 'Elevação Posterior (Crucifixo Invertido)',
    nomeIngles: 'Reverse Fly',
    descricaoMovimento: [
      'Incline o tronco a aproximadamente 45 graus (ou use banco inclinado)',
      'Segure os halteres com as palmas voltadas uma para outra',
      'Com os cotovelos levemente flexionados, abra os braços lateralmente',
      'Suba até os braços ficarem paralelos ao chão',
      'Desça controladamente',
    ],
    gruposMusculares: {
      principal: ['Deltóide posterior'],
      secundario: ['Trapézio médio', 'Romboides', 'Infraespinhal'],
    },
    imagemMovimento: '/exercises/elevacao-posterior.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-rear-delts-back.png',
    dicas: [
      'Mantenha as costas retas',
      'Foque em puxar com os cotovelos, não com as mãos',
      'Use cargas leves para manter a técnica',
    ],
    equipamento: ['Halteres'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'ombros',
  },
  {
    id: 'desenvolvimento-arnold',
    nome: 'Desenvolvimento Arnold',
    nomeIngles: 'Arnold Press',
    descricaoMovimento: [
      'Sentado, segure os halteres à frente dos ombros com palmas voltadas para você',
      'Enquanto empurra para cima, gire os pulsos para fora',
      'No topo, as palmas devem estar voltadas para frente',
      'Desça revertendo o movimento',
      'Mantenha o core contraído durante todo o exercício',
    ],
    gruposMusculares: {
      principal: ['Deltóide anterior', 'Deltóide lateral (médio)'],
      secundario: ['Tríceps braquial', 'Trapézio superior'],
    },
    imagemMovimento: '/exercises/desenvolvimento-arnold.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-shoulders-front.png',
    dicas: [
      'Movimento criado por Arnold Schwarzenegger',
      'Trabalha todas as porções do deltóide',
      'Mantenha o movimento fluido e controlado',
    ],
    equipamento: ['Halteres', 'Banco com encosto'],
    nivel: 'intermediario',
    modalidade: ['musculacao'],
    categoria: 'ombros',
  },
  {
    id: 'encolhimento',
    nome: 'Encolhimento de Ombros',
    nomeIngles: 'Shrugs',
    descricaoMovimento: [
      'Em pé, segure os halteres ou barra ao lado do corpo',
      'Eleve os ombros em direção às orelhas',
      'Segure a contração por 1-2 segundos no topo',
      'Desça controladamente',
      'Não gire os ombros, apenas movimento vertical',
    ],
    gruposMusculares: {
      principal: ['Trapézio superior'],
      secundario: ['Levantador da escápula', 'Romboides'],
    },
    imagemMovimento: '/exercises/encolhimento.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-traps-back.png',
    dicas: [
      'Não gire os ombros',
      'Use cargas que permitam amplitude completa',
      'Mantenha os braços estendidos',
    ],
    equipamento: ['Halteres ou Barra'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'ombros',
  },
  {
    id: 'remada-alta',
    nome: 'Remada Alta',
    nomeIngles: 'Upright Row',
    descricaoMovimento: [
      'Em pé, segure a barra ou halteres à frente das coxas',
      'Pegada na largura dos ombros ou um pouco mais estreita',
      'Puxe o peso para cima, liderando com os cotovelos',
      'Suba até os cotovelos ficarem na altura dos ombros',
      'Desça controladamente',
    ],
    gruposMusculares: {
      principal: ['Deltóide lateral (médio)', 'Trapézio superior'],
      secundario: ['Deltóide anterior', 'Bíceps braquial'],
    },
    imagemMovimento: '/exercises/remada-alta.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-shoulders-front.png',
    dicas: [
      'Mantenha a barra próxima ao corpo',
      'Não suba além da linha dos ombros',
      'Use pegada mais larga se sentir desconforto no ombro',
    ],
    equipamento: ['Barra ou Halteres'],
    nivel: 'intermediario',
    modalidade: ['musculacao'],
    categoria: 'ombros',
  },
  {
    id: 'pike-pushup',
    nome: 'Pike Push-up',
    nomeIngles: 'Pike Push-up',
    descricaoMovimento: [
      'Posicione-se em V invertido (quadril alto)',
      'Mãos no chão, um pouco mais largas que os ombros',
      'Desça a cabeça em direção ao chão, flexionando os cotovelos',
      'Empurre para cima até estender os braços',
      'Mantenha o quadril alto durante todo o movimento',
    ],
    gruposMusculares: {
      principal: ['Deltóide anterior', 'Deltóide lateral (médio)'],
      secundario: ['Tríceps braquial', 'Trapézio superior', 'Core'],
    },
    imagemMovimento: '/exercises/pike-pushup.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-shoulders-front.png',
    dicas: [
      'Progressão para o handstand push-up',
      'Quanto mais vertical o tronco, maior o foco nos ombros',
      'Pode elevar os pés para aumentar a dificuldade',
    ],
    equipamento: ['Nenhum (peso corporal)'],
    nivel: 'intermediario',
    modalidade: ['calistenia', 'funcional'],
    categoria: 'ombros',
  },

  // ============ BÍCEPS (6 exercícios) ============
  {
    id: 'rosca-direta',
    nome: 'Rosca Direta com Barra',
    nomeIngles: 'Barbell Curl',
    descricaoMovimento: [
      'Em pé, segure a barra com pegada supinada (palmas para cima)',
      'Braços estendidos, cotovelos próximos ao corpo',
      'Flexione os cotovelos, levando a barra em direção aos ombros',
      'Mantenha os cotovelos fixos ao lado do corpo',
      'Desça controladamente até estender os braços',
    ],
    gruposMusculares: {
      principal: ['Bíceps braquial - cabeça longa', 'Bíceps braquial - cabeça curta'],
      secundario: ['Braquial', 'Braquiorradial'],
    },
    imagemMovimento: '/exercises/rosca-direta.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-biceps-front.png',
    dicas: [
      'Não balance o corpo para levantar o peso',
      'Mantenha os cotovelos fixos',
      'Controle a fase excêntrica (descida)',
    ],
    equipamento: ['Barra reta ou W'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'biceps',
  },
  {
    id: 'rosca-alternada',
    nome: 'Rosca Alternada com Halteres',
    nomeIngles: 'Alternating Dumbbell Curl',
    descricaoMovimento: [
      'Em pé, segure os halteres ao lado do corpo com palmas neutras',
      'Flexione um braço, girando o punho para supinação durante a subida',
      'Suba até o halter chegar próximo ao ombro',
      'Desça controladamente enquanto sobe o outro braço',
      'Mantenha os cotovelos fixos ao lado do corpo',
    ],
    gruposMusculares: {
      principal: ['Bíceps braquial - cabeça longa', 'Bíceps braquial - cabeça curta'],
      secundario: ['Braquial', 'Braquiorradial'],
    },
    imagemMovimento: '/exercises/rosca-alternada.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-biceps-front.png',
    dicas: [
      'A rotação (supinação) aumenta a ativação do bíceps',
      'Não balance o tronco',
      'Pode fazer simultâneo ou alternado',
    ],
    equipamento: ['Halteres'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'biceps',
  },
  {
    id: 'rosca-martelo',
    nome: 'Rosca Martelo',
    nomeIngles: 'Hammer Curl',
    descricaoMovimento: [
      'Em pé, segure os halteres ao lado do corpo com pegada neutra',
      'Mantenha as palmas voltadas uma para outra durante todo o movimento',
      'Flexione os cotovelos, levando os halteres aos ombros',
      'Mantenha os cotovelos fixos ao lado do corpo',
      'Desça controladamente',
    ],
    gruposMusculares: {
      principal: ['Braquial', 'Braquiorradial'],
      secundario: ['Bíceps braquial - cabeça longa'],
    },
    imagemMovimento: '/exercises/rosca-martelo.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-biceps-front.png',
    dicas: [
      'Excelente para desenvolver o braquial (entre bíceps e tríceps)',
      'Não gire os punhos',
      'Trabalha bem o antebraço',
    ],
    equipamento: ['Halteres'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'biceps',
  },
  {
    id: 'rosca-concentrada',
    nome: 'Rosca Concentrada',
    nomeIngles: 'Concentration Curl',
    descricaoMovimento: [
      'Sentado, apoie o cotovelo na parte interna da coxa',
      'Segure o halter com pegada supinada',
      'Flexione o cotovelo, levando o halter ao ombro',
      'Contraia o bíceps no topo do movimento',
      'Desça controladamente até estender o braço',
    ],
    gruposMusculares: {
      principal: ['Bíceps braquial - cabeça curta'],
      secundario: ['Braquial'],
    },
    imagemMovimento: '/exercises/rosca-concentrada.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-biceps-front.png',
    dicas: [
      'Exercício de isolamento máximo',
      'Foque na contração do pico do bíceps',
      'Movimento lento e controlado',
    ],
    equipamento: ['Halter', 'Banco'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'biceps',
  },
  {
    id: 'rosca-scott',
    nome: 'Rosca Scott',
    nomeIngles: 'Preacher Curl',
    descricaoMovimento: [
      'Sente no banco Scott com os braços apoiados no suporte',
      'Segure a barra com pegada supinada',
      'Flexione os cotovelos, levando a barra aos ombros',
      'Desça controladamente até quase estender os braços',
      'Não estenda completamente para manter tensão',
    ],
    gruposMusculares: {
      principal: ['Bíceps braquial - cabeça curta'],
      secundario: ['Braquial'],
    },
    imagemMovimento: '/exercises/rosca-scott.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-biceps-front.png',
    dicas: [
      'Evita o uso de impulso',
      'Não desça completamente para proteger o cotovelo',
      'Pode usar barra reta ou W',
    ],
    equipamento: ['Banco Scott', 'Barra ou Halteres'],
    nivel: 'intermediario',
    modalidade: ['musculacao'],
    categoria: 'biceps',
  },
  {
    id: 'rosca-cabo',
    nome: 'Rosca no Cabo',
    nomeIngles: 'Cable Curl',
    descricaoMovimento: [
      'Posicione a polia na posição mais baixa',
      'Segure a barra ou manopla com pegada supinada',
      'Flexione os cotovelos, levando as mãos aos ombros',
      'Mantenha os cotovelos fixos ao lado do corpo',
      'Desça controladamente',
    ],
    gruposMusculares: {
      principal: ['Bíceps braquial - cabeça longa', 'Bíceps braquial - cabeça curta'],
      secundario: ['Braquial', 'Braquiorradial'],
    },
    imagemMovimento: '/exercises/rosca-cabo.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-biceps-front.png',
    dicas: [
      'Tensão constante durante todo o movimento',
      'Ótimo para finalização do treino',
      'Pode variar com diferentes pegadas',
    ],
    equipamento: ['Polia', 'Barra reta ou corda'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'biceps',
  },

  // ============ TRÍCEPS (6 exercícios) ============
  {
    id: 'triceps-pulley',
    nome: 'Tríceps Pulley (Corda)',
    nomeIngles: 'Tricep Pushdown',
    descricaoMovimento: [
      'Posicione a polia na posição mais alta',
      'Segure a corda com pegada neutra',
      'Mantenha os cotovelos fixos ao lado do corpo',
      'Estenda os braços para baixo, separando as pontas da corda no final',
      'Retorne controladamente até aproximadamente 90 graus',
    ],
    gruposMusculares: {
      principal: ['Tríceps braquial - cabeça lateral', 'Tríceps braquial - cabeça medial'],
      secundario: ['Tríceps braquial - cabeça longa'],
    },
    imagemMovimento: '/exercises/triceps-pulley.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-triceps-back.png',
    dicas: [
      'Não mova os cotovelos para frente ou para trás',
      'Separe a corda no final para maior contração',
      'Mantenha o tronco levemente inclinado',
    ],
    equipamento: ['Polia', 'Corda'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'triceps',
  },
  {
    id: 'triceps-testa',
    nome: 'Tríceps Testa',
    nomeIngles: 'Skull Crusher',
    descricaoMovimento: [
      'Deite no banco segurando a barra ou halteres acima do peito',
      'Flexione apenas os cotovelos, levando o peso em direção à testa',
      'Mantenha os braços superiores fixos (perpendiculares ao corpo)',
      'Estenda os cotovelos para retornar à posição inicial',
      'Controle o movimento durante toda a amplitude',
    ],
    gruposMusculares: {
      principal: ['Tríceps braquial - cabeça longa'],
      secundario: ['Tríceps braquial - cabeça lateral', 'Tríceps braquial - cabeça medial'],
    },
    imagemMovimento: '/exercises/triceps-testa.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-triceps-back.png',
    dicas: [
      'Use cargas moderadas para proteger os cotovelos',
      'Pode descer atrás da cabeça para maior alongamento',
      'Mantenha os cotovelos apontando para o teto',
    ],
    equipamento: ['Barra W ou Halteres', 'Banco'],
    nivel: 'intermediario',
    modalidade: ['musculacao'],
    categoria: 'triceps',
  },
  {
    id: 'triceps-frances',
    nome: 'Tríceps Francês',
    nomeIngles: 'Overhead Tricep Extension',
    descricaoMovimento: [
      'Sentado ou em pé, segure o halter com as duas mãos atrás da cabeça',
      'Cotovelos apontando para cima',
      'Estenda os braços, levando o halter acima da cabeça',
      'Flexione os cotovelos para retornar à posição inicial',
      'Mantenha os cotovelos próximos à cabeça',
    ],
    gruposMusculares: {
      principal: ['Tríceps braquial - cabeça longa'],
      secundario: ['Tríceps braquial - cabeça lateral', 'Tríceps braquial - cabeça medial'],
    },
    imagemMovimento: '/exercises/triceps-frances.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-triceps-back.png',
    dicas: [
      'O alongamento da cabeça longa é máximo nesta posição',
      'Não deixe os cotovelos abrirem para os lados',
      'Pode usar corda no cabo também',
    ],
    equipamento: ['Halter ou Corda'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'triceps',
  },
  {
    id: 'mergulho-triceps',
    nome: 'Mergulho no Banco',
    nomeIngles: 'Bench Dips',
    descricaoMovimento: [
      'Apoie as mãos no banco atrás de você',
      'Pernas estendidas à frente (ou flexionadas para facilitar)',
      'Desça o corpo flexionando os cotovelos até ~90 graus',
      'Empurre para cima até estender os braços',
      'Mantenha o corpo próximo ao banco',
    ],
    gruposMusculares: {
      principal: ['Tríceps braquial - cabeça lateral', 'Tríceps braquial - cabeça medial'],
      secundario: ['Deltóide anterior', 'Peitoral maior - porção abdominal (inferior)'],
    },
    imagemMovimento: '/exercises/mergulho-triceps.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-triceps-back.png',
    dicas: [
      'Não desça demais para proteger os ombros',
      'Pode adicionar peso no colo para progredir',
      'Mantenha os cotovelos apontando para trás',
    ],
    equipamento: ['Banco'],
    nivel: 'iniciante',
    modalidade: ['musculacao', 'calistenia'],
    categoria: 'triceps',
  },
  {
    id: 'dips-paralelas',
    nome: 'Dips nas Paralelas',
    nomeIngles: 'Parallel Bar Dips',
    descricaoMovimento: [
      'Segure as barras paralelas e levante o corpo',
      'Incline levemente o tronco para frente',
      'Desça flexionando os cotovelos até ~90 graus',
      'Empurre para cima até estender os braços',
      'Mantenha os cotovelos próximos ao corpo para focar no tríceps',
    ],
    gruposMusculares: {
      principal: ['Tríceps braquial', 'Peitoral maior - porção abdominal (inferior)'],
      secundario: ['Deltóide anterior'],
    },
    imagemMovimento: '/exercises/dips-paralelas.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-triceps-back.png',
    dicas: [
      'Tronco mais reto = mais tríceps; mais inclinado = mais peito',
      'Não desça além de 90 graus se sentir desconforto no ombro',
      'Pode adicionar peso com cinto',
    ],
    equipamento: ['Barras paralelas'],
    nivel: 'intermediario',
    modalidade: ['musculacao', 'calistenia'],
    categoria: 'triceps',
  },
  {
    id: 'triceps-coice',
    nome: 'Tríceps Coice',
    nomeIngles: 'Tricep Kickback',
    descricaoMovimento: [
      'Incline o tronco a aproximadamente 45-60 graus',
      'Segure o halter, braço superior paralelo ao chão',
      'Estenda o cotovelo, levando o halter para trás',
      'Contraia o tríceps no final do movimento',
      'Retorne controladamente à posição inicial',
    ],
    gruposMusculares: {
      principal: ['Tríceps braquial - cabeça lateral'],
      secundario: ['Tríceps braquial - cabeça longa', 'Tríceps braquial - cabeça medial'],
    },
    imagemMovimento: '/exercises/triceps-coice.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-triceps-back.png',
    dicas: [
      'Mantenha o braço superior fixo',
      'Use cargas leves para manter a técnica',
      'Foque na contração completa no final',
    ],
    equipamento: ['Halter'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'triceps',
  },

  // ============ PERNAS (12 exercícios) ============
  {
    id: 'agachamento',
    nome: 'Agachamento Livre',
    nomeIngles: 'Barbell Squat',
    descricaoMovimento: [
      'Posicione a barra nos trapézios (high bar) ou deltoides posteriores (low bar)',
      'Pés na largura dos ombros ou um pouco mais largos',
      'Desça flexionando quadris e joelhos simultaneamente',
      'Desça até as coxas ficarem paralelas ao chão ou mais',
      'Suba empurrando o chão e estendendo quadris e joelhos',
    ],
    gruposMusculares: {
      principal: ['Quadríceps - reto femoral', 'Quadríceps - vasto lateral', 'Quadríceps - vasto medial', 'Glúteo máximo'],
      secundario: ['Isquiotibiais', 'Eretor da espinha', 'Core', 'Adutores'],
    },
    imagemMovimento: '/exercises/agachamento.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-quads-front.png',
    dicas: [
      'Joelhos na direção dos pés',
      'Mantenha o core contraído',
      'Olhar para frente ou levemente para cima',
    ],
    equipamento: ['Barra', 'Rack', 'Anilhas'],
    nivel: 'intermediario',
    modalidade: ['musculacao'],
    categoria: 'pernas',
  },
  {
    id: 'leg-press',
    nome: 'Leg Press 45°',
    nomeIngles: 'Leg Press',
    descricaoMovimento: [
      'Sente na máquina com as costas apoiadas',
      'Posicione os pés na plataforma na largura dos ombros',
      'Destrave a plataforma e desça controladamente',
      'Flexione os joelhos até aproximadamente 90 graus',
      'Empurre a plataforma até quase estender as pernas',
    ],
    gruposMusculares: {
      principal: ['Quadríceps - reto femoral', 'Quadríceps - vasto lateral', 'Quadríceps - vasto medial'],
      secundario: ['Glúteo máximo', 'Isquiotibiais', 'Adutores'],
    },
    imagemMovimento: '/exercises/leg-press.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-quads-front.png',
    dicas: [
      'Não trave os joelhos completamente no topo',
      'Pés mais altos = mais glúteos e isquiotibiais',
      'Pés mais baixos = mais quadríceps',
    ],
    equipamento: ['Máquina Leg Press'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'pernas',
  },
  {
    id: 'extensora',
    nome: 'Cadeira Extensora',
    nomeIngles: 'Leg Extension',
    descricaoMovimento: [
      'Sente na máquina com as costas apoiadas',
      'Posicione o apoio na parte frontal dos tornozelos',
      'Estenda os joelhos até as pernas ficarem retas',
      'Contraia o quadríceps no topo',
      'Desça controladamente até aproximadamente 90 graus',
    ],
    gruposMusculares: {
      principal: ['Quadríceps - reto femoral', 'Quadríceps - vasto lateral', 'Quadríceps - vasto medial', 'Quadríceps - vasto intermédio'],
      secundario: [],
    },
    imagemMovimento: '/exercises/extensora.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-quads-front.png',
    dicas: [
      'Exercício de isolamento para o quadríceps',
      'Não use impulso',
      'Excelente para aquecimento ou finalização',
    ],
    equipamento: ['Cadeira Extensora'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'pernas',
  },
  {
    id: 'flexora',
    nome: 'Cadeira Flexora',
    nomeIngles: 'Leg Curl',
    descricaoMovimento: [
      'Deite de bruços na máquina',
      'Posicione o apoio na parte de trás dos tornozelos',
      'Flexione os joelhos, levando os calcanhares em direção aos glúteos',
      'Contraia os isquiotibiais no topo',
      'Desça controladamente',
    ],
    gruposMusculares: {
      principal: ['Isquiotibiais - bíceps femoral', 'Isquiotibiais - semitendíneo', 'Isquiotibiais - semimembranáceo'],
      secundario: ['Gastrocnêmio (panturrilha)'],
    },
    imagemMovimento: '/exercises/flexora.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-hamstrings-back.png',
    dicas: [
      'Não levante o quadril durante o movimento',
      'Mantenha o movimento lento e controlado',
      'Pode fazer unilateral para corrigir desequilíbrios',
    ],
    equipamento: ['Cadeira Flexora'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'pernas',
  },
  {
    id: 'stiff',
    nome: 'Stiff (Levantamento Terra Romeno)',
    nomeIngles: 'Romanian Deadlift',
    descricaoMovimento: [
      'Em pé, segure a barra com pegada pronada',
      'Joelhos levemente flexionados e fixos',
      'Empurre o quadril para trás enquanto desce a barra',
      'Desça até sentir alongamento nos isquiotibiais',
      'Retorne contraindo glúteos e isquiotibiais',
    ],
    gruposMusculares: {
      principal: ['Isquiotibiais', 'Glúteo máximo'],
      secundario: ['Eretor da espinha', 'Latíssimo do dorso'],
    },
    imagemMovimento: '/exercises/stiff.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-hamstrings-back.png',
    dicas: [
      'Diferente do terra, os joelhos ficam quase fixos',
      'A barra deve descer rente às pernas',
      'Não arredonde as costas',
    ],
    equipamento: ['Barra', 'Anilhas'],
    nivel: 'intermediario',
    modalidade: ['musculacao'],
    categoria: 'pernas',
  },
  {
    id: 'afundo',
    nome: 'Afundo (Passada)',
    nomeIngles: 'Lunge',
    descricaoMovimento: [
      'Em pé, dê um passo largo à frente',
      'Desça flexionando ambos os joelhos',
      'O joelho da frente deve ficar sobre o tornozelo',
      'O joelho de trás quase toca o chão',
      'Empurre com a perna da frente para retornar',
    ],
    gruposMusculares: {
      principal: ['Quadríceps - reto femoral', 'Glúteo máximo'],
      secundario: ['Isquiotibiais', 'Adutores', 'Core (estabilização)'],
    },
    imagemMovimento: '/exercises/afundo.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-quads-front.png',
    dicas: [
      'Mantenha o tronco ereto',
      'Joelho da frente não deve passar muito da ponta do pé',
      'Pode fazer estacionário, caminhando ou alternado',
    ],
    equipamento: ['Halteres ou Barra (opcional)'],
    nivel: 'iniciante',
    modalidade: ['musculacao', 'funcional'],
    categoria: 'pernas',
  },
  {
    id: 'agachamento-bulgaro',
    nome: 'Agachamento Búlgaro',
    nomeIngles: 'Bulgarian Split Squat',
    descricaoMovimento: [
      'Posicione um pé atrás em um banco',
      'Desça flexionando o joelho da frente',
      'Mantenha o tronco ereto',
      'O joelho da frente deve ficar sobre o tornozelo',
      'Empurre para cima até estender a perna da frente',
    ],
    gruposMusculares: {
      principal: ['Quadríceps - reto femoral', 'Glúteo máximo'],
      secundario: ['Isquiotibiais', 'Adutores', 'Core'],
    },
    imagemMovimento: '/exercises/agachamento-bulgaro.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-glutes-back.png',
    dicas: [
      'Excelente para corrigir desequilíbrios entre pernas',
      'Maior amplitude que o afundo tradicional',
      'Pode usar halteres ou barra',
    ],
    equipamento: ['Banco', 'Halteres (opcional)'],
    nivel: 'intermediario',
    modalidade: ['musculacao', 'funcional'],
    categoria: 'pernas',
  },
  {
    id: 'panturrilha',
    nome: 'Elevação de Panturrilha em Pé',
    nomeIngles: 'Standing Calf Raise',
    descricaoMovimento: [
      'Em pé na máquina ou step, apoio nos ombros ou segurando peso',
      'Calcanhares abaixo do nível do step (alongamento)',
      'Eleve os calcanhares o mais alto possível',
      'Contraia a panturrilha no topo',
      'Desça controladamente até alongar novamente',
    ],
    gruposMusculares: {
      principal: ['Gastrocnêmio (panturrilha)'],
      secundario: ['Sóleo'],
    },
    imagemMovimento: '/exercises/panturrilha.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-calves-back.png',
    dicas: [
      'Use amplitude completa',
      'Mantenha os joelhos levemente flexionados',
      'Pode variar a posição dos pés (reto, para dentro, para fora)',
    ],
    equipamento: ['Máquina ou Step'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'pernas',
  },
  {
    id: 'panturrilha-sentado',
    nome: 'Elevação de Panturrilha Sentado',
    nomeIngles: 'Seated Calf Raise',
    descricaoMovimento: [
      'Sente na máquina com os joelhos sob os apoios',
      'Calcanhares abaixo do nível da plataforma',
      'Eleve os calcanhares o mais alto possível',
      'Contraia no topo',
      'Desça controladamente',
    ],
    gruposMusculares: {
      principal: ['Sóleo'],
      secundario: ['Gastrocnêmio (panturrilha)'],
    },
    imagemMovimento: '/exercises/panturrilha-sentado.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-calves-back.png',
    dicas: [
      'Com os joelhos flexionados, foca mais no sóleo',
      'Complementa a elevação em pé',
      'Use amplitude completa',
    ],
    equipamento: ['Máquina de panturrilha sentado'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'pernas',
  },
  {
    id: 'hack-squat',
    nome: 'Hack Squat',
    nomeIngles: 'Hack Squat',
    descricaoMovimento: [
      'Posicione-se na máquina com as costas apoiadas',
      'Pés na plataforma na largura dos ombros',
      'Destrave e desça flexionando os joelhos',
      'Desça até aproximadamente 90 graus',
      'Empurre para cima até quase estender as pernas',
    ],
    gruposMusculares: {
      principal: ['Quadríceps - reto femoral', 'Quadríceps - vasto lateral', 'Quadríceps - vasto medial'],
      secundario: ['Glúteo máximo'],
    },
    imagemMovimento: '/exercises/hack-squat.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-quads-front.png',
    dicas: [
      'Ótima alternativa ao agachamento livre',
      'Menor demanda de estabilização',
      'Posição dos pés altera o foco muscular',
    ],
    equipamento: ['Máquina Hack Squat'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'pernas',
  },
  {
    id: 'adutora',
    nome: 'Cadeira Adutora',
    nomeIngles: 'Adductor Machine',
    descricaoMovimento: [
      'Sente na máquina com as pernas abertas',
      'Posicione a parte interna das coxas nos apoios',
      'Traga as pernas juntas, contraindo os adutores',
      'Segure a contração por 1-2 segundos',
      'Retorne controladamente à posição inicial',
    ],
    gruposMusculares: {
      principal: ['Adutores'],
      secundario: ['Glúteo médio'],
    },
    imagemMovimento: '/exercises/adutora.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-adductors-front.png',
    dicas: [
      'Movimento lento e controlado',
      'Não use impulso',
      'Excelente para fortalecimento da parte interna da coxa',
    ],
    equipamento: ['Cadeira Adutora'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'pernas',
  },
  {
    id: 'abdutora',
    nome: 'Cadeira Abdutora',
    nomeIngles: 'Abductor Machine',
    descricaoMovimento: [
      'Sente na máquina com as pernas juntas',
      'Posicione a parte externa das coxas nos apoios',
      'Abra as pernas, contraindo os abdutores',
      'Segure a contração por 1-2 segundos',
      'Retorne controladamente à posição inicial',
    ],
    gruposMusculares: {
      principal: ['Glúteo médio', 'Abdutores'],
      secundario: ['Glúteo mínimo'],
    },
    imagemMovimento: '/exercises/abdutora.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-glutes-back.png',
    dicas: [
      'Importante para estabilidade do quadril',
      'Não use cargas excessivas',
      'Mantenha as costas apoiadas',
    ],
    equipamento: ['Cadeira Abdutora'],
    nivel: 'iniciante',
    modalidade: ['musculacao'],
    categoria: 'pernas',
  },

  // ============ CORE (8 exercícios) ============
  {
    id: 'prancha',
    nome: 'Prancha Frontal',
    nomeIngles: 'Plank',
    descricaoMovimento: [
      'Apoie os antebraços e pontas dos pés no chão',
      'Mantenha o corpo em linha reta da cabeça aos pés',
      'Contraia o abdômen e glúteos',
      'Não deixe o quadril subir ou descer',
      'Mantenha a posição pelo tempo determinado',
    ],
    gruposMusculares: {
      principal: ['Reto abdominal', 'Transverso do abdômen'],
      secundario: ['Oblíquos', 'Eretor da espinha', 'Glúteos', 'Deltóides'],
    },
    imagemMovimento: '/exercises/prancha.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-abs-front.png',
    dicas: [
      'Não prenda a respiração',
      'Imagine puxar o umbigo em direção à coluna',
      'Olhe para o chão, mantendo o pescoço neutro',
    ],
    equipamento: ['Nenhum'],
    nivel: 'iniciante',
    modalidade: ['funcional', 'calistenia'],
    categoria: 'core',
  },
  {
    id: 'abdominal-crunch',
    nome: 'Abdominal Crunch',
    nomeIngles: 'Crunch',
    descricaoMovimento: [
      'Deite com os joelhos flexionados, pés no chão',
      'Mãos atrás da cabeça ou cruzadas no peito',
      'Eleve os ombros do chão, contraindo o abdômen',
      'Não puxe o pescoço com as mãos',
      'Desça controladamente sem relaxar completamente',
    ],
    gruposMusculares: {
      principal: ['Reto abdominal'],
      secundario: ['Oblíquos'],
    },
    imagemMovimento: '/exercises/abdominal-crunch.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-abs-front.png',
    dicas: [
      'Amplitude pequena é suficiente',
      'Foque na contração do abdômen',
      'Não force o pescoço',
    ],
    equipamento: ['Nenhum'],
    nivel: 'iniciante',
    modalidade: ['musculacao', 'funcional'],
    categoria: 'core',
  },
  {
    id: 'prancha-lateral',
    nome: 'Prancha Lateral',
    nomeIngles: 'Side Plank',
    descricaoMovimento: [
      'Deite de lado, apoiando o antebraço no chão',
      'Eleve o quadril, alinhando o corpo da cabeça aos pés',
      'Mantenha o cotovelo sob o ombro',
      'O braço de cima pode ficar no quadril ou estendido',
      'Mantenha a posição e repita do outro lado',
    ],
    gruposMusculares: {
      principal: ['Oblíquos externos', 'Oblíquos internos'],
      secundario: ['Quadrado lombar', 'Glúteo médio', 'Transverso do abdômen'],
    },
    imagemMovimento: '/exercises/prancha-lateral.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-obliques-front.png',
    dicas: [
      'Não deixe o quadril cair',
      'Pode flexionar o joelho de baixo para facilitar',
      'Trabalha muito os estabilizadores laterais',
    ],
    equipamento: ['Nenhum'],
    nivel: 'iniciante',
    modalidade: ['funcional', 'calistenia'],
    categoria: 'core',
  },
  {
    id: 'russian-twist',
    nome: 'Russian Twist',
    nomeIngles: 'Russian Twist',
    descricaoMovimento: [
      'Sente com os joelhos flexionados, pés elevados ou no chão',
      'Incline o tronco levemente para trás',
      'Segure um peso com as duas mãos à frente do peito',
      'Gire o tronco para um lado, depois para o outro',
      'Mantenha o abdômen contraído durante todo o movimento',
    ],
    gruposMusculares: {
      principal: ['Oblíquos externos', 'Oblíquos internos'],
      secundario: ['Reto abdominal', 'Transverso do abdômen'],
    },
    imagemMovimento: '/exercises/russian-twist.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-obliques-front.png',
    dicas: [
      'Gire o tronco, não apenas os braços',
      'Pode fazer com ou sem peso',
      'Elevar os pés aumenta a dificuldade',
    ],
    equipamento: ['Peso (opcional)'],
    nivel: 'iniciante',
    modalidade: ['funcional'],
    categoria: 'core',
  },
  {
    id: 'leg-raise',
    nome: 'Elevação de Pernas',
    nomeIngles: 'Leg Raise',
    descricaoMovimento: [
      'Deite de costas com as mãos sob os glúteos ou ao lado',
      'Pernas estendidas juntas',
      'Eleve as pernas até ficarem perpendiculares ao chão',
      'Desça controladamente sem tocar o chão',
      'Mantenha a lombar pressionada contra o chão',
    ],
    gruposMusculares: {
      principal: ['Reto abdominal (porção inferior)', 'Psoas ilíaco'],
      secundario: ['Quadríceps'],
    },
    imagemMovimento: '/exercises/leg-raise.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-abs-front.png',
    dicas: [
      'Se a lombar sair do chão, flexione levemente os joelhos',
      'Pode fazer na barra fixa (pendurado)',
      'Controle a descida para maior efetividade',
    ],
    equipamento: ['Nenhum'],
    nivel: 'intermediario',
    modalidade: ['funcional', 'calistenia'],
    categoria: 'core',
  },
  {
    id: 'mountain-climber',
    nome: 'Mountain Climber',
    nomeIngles: 'Mountain Climber',
    descricaoMovimento: [
      'Posição de prancha alta (braços estendidos)',
      'Traga um joelho em direção ao peito',
      'Retorne e traga o outro joelho',
      'Alterne rapidamente mantendo o core estável',
      'Mantenha o quadril baixo e alinhado',
    ],
    gruposMusculares: {
      principal: ['Reto abdominal', 'Psoas ilíaco'],
      secundario: ['Deltóides', 'Quadríceps', 'Tríceps', 'Core (estabilização)'],
    },
    imagemMovimento: '/exercises/mountain-climber.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-abs-front.png',
    dicas: [
      'Excelente para cardio e core simultaneamente',
      'Não deixe o quadril subir',
      'Pode variar a velocidade conforme objetivo',
    ],
    equipamento: ['Nenhum'],
    nivel: 'iniciante',
    modalidade: ['funcional', 'crossfit'],
    categoria: 'core',
  },
  {
    id: 'abdominal-bicicleta',
    nome: 'Abdominal Bicicleta',
    nomeIngles: 'Bicycle Crunch',
    descricaoMovimento: [
      'Deite com as mãos atrás da cabeça',
      'Eleve as pernas com joelhos flexionados a 90 graus',
      'Gire o tronco levando o cotovelo ao joelho oposto',
      'Estenda a outra perna simultaneamente',
      'Alterne os lados em movimento de pedalar',
    ],
    gruposMusculares: {
      principal: ['Oblíquos externos', 'Oblíquos internos', 'Reto abdominal'],
      secundario: ['Psoas ilíaco'],
    },
    imagemMovimento: '/exercises/abdominal-bicicleta.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-obliques-front.png',
    dicas: [
      'Movimento lento e controlado é mais efetivo',
      'Não puxe o pescoço',
      'Foque na rotação do tronco',
    ],
    equipamento: ['Nenhum'],
    nivel: 'iniciante',
    modalidade: ['funcional'],
    categoria: 'core',
  },
  {
    id: 'hollow-body',
    nome: 'Hollow Body Hold',
    nomeIngles: 'Hollow Body Hold',
    descricaoMovimento: [
      'Deite de costas com braços estendidos atrás da cabeça',
      'Pernas estendidas e juntas',
      'Eleve braços, cabeça e pernas do chão',
      'Pressione a lombar contra o chão',
      'Mantenha a posição formando um "C" com o corpo',
    ],
    gruposMusculares: {
      principal: ['Reto abdominal', 'Transverso do abdômen'],
      secundario: ['Psoas ilíaco', 'Quadríceps'],
    },
    imagemMovimento: '/exercises/hollow-body.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-abs-front.png',
    dicas: [
      'Base da ginástica e calistenia',
      'Se muito difícil, flexione os joelhos',
      'Lombar deve ficar sempre no chão',
    ],
    equipamento: ['Nenhum'],
    nivel: 'intermediario',
    modalidade: ['calistenia', 'funcional'],
    categoria: 'core',
  },

  // ============ CARDIO/FUNCIONAL (10 exercícios) ============
  {
    id: 'burpee',
    nome: 'Burpee',
    nomeIngles: 'Burpee',
    descricaoMovimento: [
      'Em pé, agache e coloque as mãos no chão',
      'Salte os pés para trás em posição de prancha',
      'Faça uma flexão (opcional)',
      'Salte os pés de volta para as mãos',
      'Salte verticalmente com os braços acima da cabeça',
    ],
    gruposMusculares: {
      principal: ['Quadríceps', 'Peitoral maior', 'Deltóides'],
      secundario: ['Core', 'Tríceps', 'Isquiotibiais', 'Glúteos'],
    },
    imagemMovimento: '/exercises/burpee.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-full-body-front.png',
    dicas: [
      'Exercício de corpo inteiro de alta intensidade',
      'Pode eliminar a flexão para facilitar',
      'Mantenha o core contraído na prancha',
    ],
    equipamento: ['Nenhum'],
    nivel: 'intermediario',
    modalidade: ['funcional', 'crossfit'],
    categoria: 'cardio',
  },
  {
    id: 'jumping-jack',
    nome: 'Jumping Jack',
    nomeIngles: 'Jumping Jack',
    descricaoMovimento: [
      'Em pé com os pés juntos e braços ao lado',
      'Salte abrindo as pernas e elevando os braços',
      'As mãos devem se encontrar acima da cabeça',
      'Salte novamente retornando à posição inicial',
      'Mantenha um ritmo constante',
    ],
    gruposMusculares: {
      principal: ['Quadríceps', 'Gastrocnêmio (panturrilha)'],
      secundario: ['Deltóides', 'Adutores', 'Abdutores'],
    },
    imagemMovimento: '/exercises/jumping-jack.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-full-body-front.png',
    dicas: [
      'Excelente para aquecimento',
      'Aterrisse suavemente para proteger as articulações',
      'Pode ser feito de forma lenta ou rápida',
    ],
    equipamento: ['Nenhum'],
    nivel: 'iniciante',
    modalidade: ['funcional', 'cardio'],
    categoria: 'cardio',
  },
  {
    id: 'box-jump',
    nome: 'Box Jump',
    nomeIngles: 'Box Jump',
    descricaoMovimento: [
      'Posicione-se em frente a uma caixa ou banco',
      'Flexione levemente os joelhos e balance os braços',
      'Salte explosivamente sobre a caixa',
      'Aterrisse com os dois pés no centro da caixa',
      'Estenda completamente e desça controladamente',
    ],
    gruposMusculares: {
      principal: ['Quadríceps', 'Glúteo máximo', 'Gastrocnêmio (panturrilha)'],
      secundario: ['Isquiotibiais', 'Core'],
    },
    imagemMovimento: '/exercises/box-jump.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-quads-front.png',
    dicas: [
      'Comece com uma altura baixa',
      'Aterrisse suavemente com os joelhos flexionados',
      'Pode descer andando ou pulando',
    ],
    equipamento: ['Caixa pliométrica'],
    nivel: 'intermediario',
    modalidade: ['funcional', 'crossfit'],
    categoria: 'cardio',
  },
  {
    id: 'kettlebell-swing',
    nome: 'Kettlebell Swing',
    nomeIngles: 'Kettlebell Swing',
    descricaoMovimento: [
      'Em pé, pés um pouco mais largos que os ombros',
      'Segure o kettlebell com as duas mãos à frente',
      'Empurre o quadril para trás, balançando o kettlebell entre as pernas',
      'Estenda o quadril explosivamente, projetando o kettlebell à frente',
      'Deixe o kettlebell voltar e repita o movimento',
    ],
    gruposMusculares: {
      principal: ['Glúteo máximo', 'Isquiotibiais'],
      secundario: ['Core', 'Eretor da espinha', 'Deltóides', 'Antebraços'],
    },
    imagemMovimento: '/exercises/kettlebell-swing.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-glutes-back.png',
    dicas: [
      'O movimento vem do quadril, não dos braços',
      'Mantenha as costas retas',
      'Os braços servem apenas para segurar o peso',
    ],
    equipamento: ['Kettlebell'],
    nivel: 'intermediario',
    modalidade: ['funcional', 'crossfit'],
    categoria: 'cardio',
  },
  {
    id: 'agachamento-salto',
    nome: 'Agachamento com Salto',
    nomeIngles: 'Jump Squat',
    descricaoMovimento: [
      'Em pé, pés na largura dos ombros',
      'Agache até as coxas ficarem paralelas ao chão',
      'Salte explosivamente, estendendo completamente',
      'Aterrisse suavemente e vá direto para o próximo agachamento',
      'Use os braços para ajudar no impulso',
    ],
    gruposMusculares: {
      principal: ['Quadríceps', 'Glúteo máximo'],
      secundario: ['Isquiotibiais', 'Gastrocnêmio (panturrilha)', 'Core'],
    },
    imagemMovimento: '/exercises/agachamento-salto.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-quads-front.png',
    dicas: [
      'Aterrisse com os joelhos levemente flexionados',
      'Mantenha o peito erguido',
      'Excelente para potência de pernas',
    ],
    equipamento: ['Nenhum'],
    nivel: 'intermediario',
    modalidade: ['funcional', 'crossfit'],
    categoria: 'cardio',
  },
  {
    id: 'skater',
    nome: 'Skater Jump',
    nomeIngles: 'Skater',
    descricaoMovimento: [
      'Em pé, salte lateralmente para um lado',
      'Aterrisse em uma perna, levando a outra atrás',
      'Toque o chão com a mão oposta (opcional)',
      'Salte para o outro lado',
      'Alterne em movimento de patinação',
    ],
    gruposMusculares: {
      principal: ['Glúteo médio', 'Quadríceps'],
      secundario: ['Abdutores', 'Adutores', 'Core (estabilização)'],
    },
    imagemMovimento: '/exercises/skater.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-glutes-back.png',
    dicas: [
      'Excelente para estabilidade lateral',
      'Trabalha muito os glúteos médios',
      'Mantenha o core contraído',
    ],
    equipamento: ['Nenhum'],
    nivel: 'intermediario',
    modalidade: ['funcional'],
    categoria: 'cardio',
  },
  {
    id: 'wall-ball',
    nome: 'Wall Ball',
    nomeIngles: 'Wall Ball',
    descricaoMovimento: [
      'Em pé, de frente para uma parede, segurando uma medicine ball',
      'Agache segurando a bola na altura do peito',
      'Levante explosivamente, arremessando a bola para cima na parede',
      'Receba a bola e agache novamente em um movimento fluido',
      'Repita sem pausa entre as repetições',
    ],
    gruposMusculares: {
      principal: ['Quadríceps', 'Glúteo máximo', 'Deltóides'],
      secundario: ['Core', 'Tríceps', 'Trapézio'],
    },
    imagemMovimento: '/exercises/wall-ball.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-full-body-front.png',
    dicas: [
      'Exercício clássico de CrossFit',
      'Mantenha um ritmo constante',
      'Alvo geralmente a 3m de altura',
    ],
    equipamento: ['Medicine Ball', 'Parede'],
    nivel: 'intermediario',
    modalidade: ['crossfit', 'funcional'],
    categoria: 'cardio',
  },
  {
    id: 'thruster',
    nome: 'Thruster',
    nomeIngles: 'Thruster',
    descricaoMovimento: [
      'Segure a barra ou halteres na posição de front squat',
      'Agache até as coxas ficarem paralelas ao chão',
      'Levante explosivamente, empurrando o peso acima da cabeça',
      'Desça o peso e agache novamente em um movimento fluido',
      'Mantenha o core contraído durante todo o movimento',
    ],
    gruposMusculares: {
      principal: ['Quadríceps', 'Glúteo máximo', 'Deltóides'],
      secundario: ['Core', 'Tríceps', 'Trapézio superior'],
    },
    imagemMovimento: '/exercises/thruster.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-full-body-front.png',
    dicas: [
      'Combina front squat com desenvolvimento',
      'Use o impulso das pernas para empurrar o peso',
      'Ótimo para condicionamento metabólico',
    ],
    equipamento: ['Barra ou Halteres'],
    nivel: 'avancado',
    modalidade: ['crossfit', 'funcional'],
    categoria: 'cardio',
  },
  {
    id: 'rope-battle',
    nome: 'Battle Rope',
    nomeIngles: 'Battle Rope Waves',
    descricaoMovimento: [
      'Em pé, segure uma ponta da corda em cada mão',
      'Flexione levemente os joelhos',
      'Alterne os braços criando ondas na corda',
      'Mantenha o movimento rápido e contínuo',
      'O core deve permanecer estável',
    ],
    gruposMusculares: {
      principal: ['Deltóides', 'Bíceps braquial', 'Core'],
      secundario: ['Antebraços', 'Peitoral maior', 'Latíssimo do dorso'],
    },
    imagemMovimento: '/exercises/rope-battle.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-shoulders-front.png',
    dicas: [
      'Excelente para condicionamento de membros superiores',
      'Varie entre ondas alternadas, simultâneas e laterais',
      'Mantenha os ombros para baixo',
    ],
    equipamento: ['Battle Rope'],
    nivel: 'intermediario',
    modalidade: ['funcional', 'crossfit'],
    categoria: 'cardio',
  },
  {
    id: 'corrida-esteira',
    nome: 'Corrida na Esteira',
    nomeIngles: 'Treadmill Running',
    descricaoMovimento: [
      'Ajuste a velocidade e inclinação desejadas',
      'Comece com uma caminhada de aquecimento',
      'Aumente gradualmente para o ritmo de corrida',
      'Mantenha postura ereta, olhando para frente',
      'Aterrisse com o meio do pé, não com o calcanhar',
    ],
    gruposMusculares: {
      principal: ['Quadríceps', 'Isquiotibiais', 'Gastrocnêmio (panturrilha)'],
      secundario: ['Glúteo máximo', 'Core', 'Psoas ilíaco'],
    },
    imagemMovimento: '/exercises/corrida-esteira.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-quads-front.png',
    dicas: [
      'Comece devagar e aumente gradualmente',
      'Use inclinação de 1-2% para simular corrida ao ar livre',
      'Hidrate-se adequadamente',
    ],
    equipamento: ['Esteira'],
    nivel: 'iniciante',
    modalidade: ['corrida', 'cardio'],
    categoria: 'cardio',
  },

  // ============ CALISTENIA (8 exercícios adicionais) ============
  {
    id: 'muscle-up',
    nome: 'Muscle Up',
    nomeIngles: 'Muscle Up',
    descricaoMovimento: [
      'Pendure-se na barra com pegada falsa (polegares por cima)',
      'Puxe explosivamente, trazendo o peito até a barra',
      'Transicione girando os punhos sobre a barra',
      'Empurre para cima até estender os braços',
      'Desça controladamente',
    ],
    gruposMusculares: {
      principal: ['Latíssimo do dorso', 'Peitoral maior', 'Tríceps braquial'],
      secundario: ['Bíceps braquial', 'Deltóides', 'Core'],
    },
    imagemMovimento: '/exercises/muscle-up.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-lats-back.png',
    dicas: [
      'Movimento avançado que requer força de puxada e empurrar',
      'Pratique pull-ups e dips antes',
      'A transição é a parte mais difícil',
    ],
    equipamento: ['Barra fixa'],
    nivel: 'avancado',
    modalidade: ['calistenia'],
    categoria: 'calistenia',
  },
  {
    id: 'pistol-squat',
    nome: 'Pistol Squat',
    nomeIngles: 'Pistol Squat',
    descricaoMovimento: [
      'Em pé, estenda uma perna à frente',
      'Agache sobre a perna de apoio até a coxa tocar a panturrilha',
      'Mantenha a perna estendida paralela ao chão',
      'Suba controladamente sem apoiar a perna livre',
      'Mantenha os braços à frente para equilíbrio',
    ],
    gruposMusculares: {
      principal: ['Quadríceps - reto femoral', 'Glúteo máximo'],
      secundario: ['Core (estabilização)', 'Isquiotibiais', 'Psoas ilíaco'],
    },
    imagemMovimento: '/exercises/pistol-squat.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-quads-front.png',
    dicas: [
      'Requer força, mobilidade e equilíbrio',
      'Pratique com apoio (TRX, parede) inicialmente',
      'Trabalhe mobilidade de tornozelo',
    ],
    equipamento: ['Nenhum'],
    nivel: 'avancado',
    modalidade: ['calistenia'],
    categoria: 'calistenia',
  },
  {
    id: 'handstand',
    nome: 'Parada de Mãos',
    nomeIngles: 'Handstand',
    descricaoMovimento: [
      'Coloque as mãos no chão, largura dos ombros',
      'Impulsione as pernas para cima',
      'Equilibre-se com o corpo em linha reta',
      'Dedos abertos para ajudar no equilíbrio',
      'Mantenha o core e glúteos contraídos',
    ],
    gruposMusculares: {
      principal: ['Deltóides', 'Trapézio superior', 'Core'],
      secundario: ['Tríceps braquial', 'Serrátil anterior', 'Antebraços'],
    },
    imagemMovimento: '/exercises/handstand.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-shoulders-front.png',
    dicas: [
      'Pratique contra a parede primeiro',
      'Olhe para as mãos, não para o chão',
      'Pequenos ajustes nos dedos controlam o equilíbrio',
    ],
    equipamento: ['Parede (para apoio)'],
    nivel: 'avancado',
    modalidade: ['calistenia'],
    categoria: 'calistenia',
  },
  {
    id: 'l-sit',
    nome: 'L-Sit',
    nomeIngles: 'L-Sit',
    descricaoMovimento: [
      'Sentado, coloque as mãos ao lado dos quadris (paraletas ou chão)',
      'Empurre para baixo, levantando o corpo do chão',
      'Estenda as pernas à frente, paralelas ao chão',
      'Mantenha o corpo em formato de L',
      'Segure a posição pelo tempo determinado',
    ],
    gruposMusculares: {
      principal: ['Reto abdominal', 'Psoas ilíaco', 'Quadríceps'],
      secundario: ['Tríceps braquial', 'Deltóides', 'Serrátil anterior'],
    },
    imagemMovimento: '/exercises/l-sit.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-abs-front.png',
    dicas: [
      'Comece com joelhos flexionados (tuck L-sit)',
      'Trabalhe mobilidade de isquiotibiais',
      'Paraletas facilitam (mais altura)',
    ],
    equipamento: ['Paraletas (opcional)'],
    nivel: 'avancado',
    modalidade: ['calistenia'],
    categoria: 'calistenia',
  },
  {
    id: 'flexao-archer',
    nome: 'Flexão Archer',
    nomeIngles: 'Archer Push-up',
    descricaoMovimento: [
      'Posição de flexão com as mãos bem afastadas',
      'Desça o corpo para um lado, estendendo o braço oposto',
      'O braço estendido fica reto, paralelo ao chão',
      'Empurre de volta ao centro',
      'Repita para o outro lado',
    ],
    gruposMusculares: {
      principal: ['Peitoral maior', 'Tríceps braquial'],
      secundario: ['Deltóide anterior', 'Core'],
    },
    imagemMovimento: '/exercises/flexao-archer.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-chest-front.png',
    dicas: [
      'Progressão para flexão unilateral',
      'Foca mais carga em um braço de cada vez',
      'Mantenha o core contraído',
    ],
    equipamento: ['Nenhum'],
    nivel: 'avancado',
    modalidade: ['calistenia'],
    categoria: 'calistenia',
  },
  {
    id: 'chin-up',
    nome: 'Chin-up (Barra Supinada)',
    nomeIngles: 'Chin-up',
    descricaoMovimento: [
      'Segure a barra com pegada supinada (palmas para você)',
      'Puxe o corpo até o queixo ultrapassar a barra',
      'Mantenha os cotovelos próximos ao corpo',
      'Desça controladamente até estender os braços',
      'Mantenha o core contraído',
    ],
    gruposMusculares: {
      principal: ['Bíceps braquial', 'Latíssimo do dorso'],
      secundario: ['Braquial', 'Romboides', 'Trapézio inferior'],
    },
    imagemMovimento: '/exercises/chin-up.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-biceps-front.png',
    dicas: [
      'Mais fácil que pull-up devido ao maior uso de bíceps',
      'Boa progressão para pull-ups',
      'Evite balançar o corpo',
    ],
    equipamento: ['Barra fixa'],
    nivel: 'intermediario',
    modalidade: ['calistenia', 'musculacao'],
    categoria: 'calistenia',
  },
  {
    id: 'toes-to-bar',
    nome: 'Toes to Bar',
    nomeIngles: 'Toes to Bar',
    descricaoMovimento: [
      'Pendure-se na barra com pegada pronada',
      'Com as pernas juntas, eleve-as até tocar a barra',
      'Mantenha os braços estendidos durante o movimento',
      'Desça as pernas controladamente',
      'Use um leve kipping para eficiência (CrossFit)',
    ],
    gruposMusculares: {
      principal: ['Reto abdominal', 'Psoas ilíaco'],
      secundario: ['Latíssimo do dorso', 'Antebraços', 'Quadríceps'],
    },
    imagemMovimento: '/exercises/toes-to-bar.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-abs-front.png',
    dicas: [
      'Exercício avançado de core',
      'Pratique knee raises primeiro',
      'Versão estrita é mais difícil que com kipping',
    ],
    equipamento: ['Barra fixa'],
    nivel: 'avancado',
    modalidade: ['calistenia', 'crossfit'],
    categoria: 'calistenia',
  },
  {
    id: 'dragon-flag',
    nome: 'Dragon Flag',
    nomeIngles: 'Dragon Flag',
    descricaoMovimento: [
      'Deite no banco, segurando a extremidade atrás da cabeça',
      'Eleve as pernas e tronco, deixando apenas os ombros no banco',
      'Mantenha o corpo em linha reta',
      'Desça controladamente sem tocar o banco',
      'Pare antes de tocar e suba novamente',
    ],
    gruposMusculares: {
      principal: ['Reto abdominal', 'Transverso do abdômen'],
      secundario: ['Psoas ilíaco', 'Latíssimo do dorso', 'Tríceps braquial'],
    },
    imagemMovimento: '/exercises/dragon-flag.gif',
    imagemMusculos: 'https://www.musclewiki.com/media/uploads/muscle-highlights/male-abs-front.png',
    dicas: [
      'Exercício popularizado por Bruce Lee',
      'Extremamente desafiador para o core',
      'Comece com negativas (apenas fase de descida)',
    ],
    equipamento: ['Banco'],
    nivel: 'avancado',
    modalidade: ['calistenia'],
    categoria: 'calistenia',
  },
];

/**
 * Get exercises by category
 */
export function getExercisesByCategory(categoria: ExerciseInfo['categoria']): ExerciseInfo[] {
  return EXERCISE_DATABASE.filter(ex => ex.categoria === categoria);
}

/**
 * Get exercises by modality
 */
export function getExercisesByModality(modalidade: string): ExerciseInfo[] {
  return EXERCISE_DATABASE.filter(ex => ex.modalidade.includes(modalidade));
}

/**
 * Get exercises by muscle group
 */
export function getExercisesByMuscleGroup(muscleGroup: string): ExerciseInfo[] {
  const lowerGroup = muscleGroup.toLowerCase();
  return EXERCISE_DATABASE.filter(ex =>
    ex.gruposMusculares.principal.some(m => m.toLowerCase().includes(lowerGroup)) ||
    ex.gruposMusculares.secundario.some(m => m.toLowerCase().includes(lowerGroup))
  );
}

/**
 * Get exercise by ID
 */
export function getExerciseById(id: string): ExerciseInfo | undefined {
  return EXERCISE_DATABASE.find(ex => ex.id === id);
}

/**
 * Get exercise by name (partial match)
 */
export function getExerciseByName(nome: string): ExerciseInfo | undefined {
  const lowerNome = nome.toLowerCase();
  return EXERCISE_DATABASE.find(ex =>
    ex.nome.toLowerCase().includes(lowerNome) ||
    ex.nomeIngles.toLowerCase().includes(lowerNome)
  );
}

/**
 * Search exercises
 */
export function searchExercises(query: string): ExerciseInfo[] {
  const lowerQuery = query.toLowerCase();
  return EXERCISE_DATABASE.filter(ex =>
    ex.nome.toLowerCase().includes(lowerQuery) ||
    ex.nomeIngles.toLowerCase().includes(lowerQuery) ||
    ex.categoria.toLowerCase().includes(lowerQuery) ||
    ex.modalidade.some(m => m.toLowerCase().includes(lowerQuery)) ||
    ex.gruposMusculares.principal.some(m => m.toLowerCase().includes(lowerQuery)) ||
    ex.gruposMusculares.secundario.some(m => m.toLowerCase().includes(lowerQuery))
  );
}
