// Lista de cidades brasileiras por estado para dropdown
// Principais cidades de cada estado

export const BRAZILIAN_CITIES: Record<string, string[]> = {
  AC: [
    'Rio Branco',
    'Cruzeiro do Sul',
    'Sena Madureira',
    'Tarauaca',
    'Feijo',
    'Brasileia',
    'Epitaciolandia',
    'Xapuri',
    'Placido de Castro',
    'Senador Guiomard',
  ],
  AL: [
    'Maceio',
    'Arapiraca',
    'Rio Largo',
    'Palmeira dos Indios',
    'Penedo',
    'Sao Miguel dos Campos',
    'Uniao dos Palmares',
    'Coruripe',
    'Delmiro Gouveia',
    'Campo Alegre',
  ],
  AP: [
    'Macapa',
    'Santana',
    'Laranjal do Jari',
    'Oiapoque',
    'Mazagao',
    'Porto Grande',
    'Tartarugalzinho',
    'Pedra Branca do Amapari',
    'Vitoria do Jari',
    'Calcoene',
  ],
  AM: [
    'Manaus',
    'Parintins',
    'Itacoatiara',
    'Manacapuru',
    'Coari',
    'Tefe',
    'Tabatinga',
    'Maues',
    'Iranduba',
    'Presidente Figueiredo',
  ],
  BA: [
    'Salvador',
    'Feira de Santana',
    'Vitoria da Conquista',
    'Camacari',
    'Itabuna',
    'Juazeiro',
    'Lauro de Freitas',
    'Ilheus',
    'Jequie',
    'Teixeira de Freitas',
    'Barreiras',
    'Porto Seguro',
    'Simoes Filho',
    'Paulo Afonso',
    'Alagoinhas',
  ],
  CE: [
    'Fortaleza',
    'Caucaia',
    'Juazeiro do Norte',
    'Maracanau',
    'Sobral',
    'Crato',
    'Itapipoca',
    'Maranguape',
    'Iguatu',
    'Quixada',
    'Pacatuba',
    'Aquiraz',
    'Caninde',
    'Russas',
    'Tiangua',
  ],
  DF: ['Brasilia'],
  ES: [
    'Vitoria',
    'Vila Velha',
    'Serra',
    'Cariacica',
    'Cachoeiro de Itapemirim',
    'Linhares',
    'Sao Mateus',
    'Colatina',
    'Guarapari',
    'Aracruz',
  ],
  GO: [
    'Goiania',
    'Aparecida de Goiania',
    'Anapolis',
    'Rio Verde',
    'Luziania',
    'Aguas Lindas de Goias',
    'Valparaiso de Goias',
    'Trindade',
    'Formosa',
    'Novo Gama',
    'Itumbiara',
    'Senador Canedo',
    'Catalao',
    'Jatai',
    'Planaltina',
  ],
  MA: [
    'Sao Luis',
    'Imperatriz',
    'Sao Jose de Ribamar',
    'Timon',
    'Caxias',
    'Codó',
    'Paco do Lumiar',
    'Acailandia',
    'Bacabal',
    'Santa Ines',
  ],
  MT: [
    'Cuiaba',
    'Varzea Grande',
    'Rondonopolis',
    'Sinop',
    'Tangara da Serra',
    'Caceres',
    'Sorriso',
    'Lucas do Rio Verde',
    'Primavera do Leste',
    'Barra do Garcas',
  ],
  MS: [
    'Campo Grande',
    'Dourados',
    'Tres Lagoas',
    'Corumba',
    'Ponta Pora',
    'Naviraí',
    'Nova Andradina',
    'Aquidauana',
    'Sidrolandia',
    'Paranaiba',
  ],
  MG: [
    'Belo Horizonte',
    'Uberlandia',
    'Contagem',
    'Juiz de Fora',
    'Betim',
    'Montes Claros',
    'Ribeirao das Neves',
    'Uberaba',
    'Governador Valadares',
    'Ipatinga',
    'Sete Lagoas',
    'Divinopolis',
    'Santa Luzia',
    'Ibirite',
    'Pocos de Caldas',
    'Patos de Minas',
    'Pouso Alegre',
    'Teofilo Otoni',
    'Barbacena',
    'Sabara',
  ],
  PA: [
    'Belem',
    'Ananindeua',
    'Santarem',
    'Maraba',
    'Parauapebas',
    'Castanhal',
    'Abaetetuba',
    'Cameta',
    'Braganca',
    'Altamira',
  ],
  PB: [
    'Joao Pessoa',
    'Campina Grande',
    'Santa Rita',
    'Patos',
    'Bayeux',
    'Sousa',
    'Cajazeiras',
    'Cabedelo',
    'Guarabira',
    'Sape',
  ],
  PR: [
    'Curitiba',
    'Londrina',
    'Maringa',
    'Ponta Grossa',
    'Cascavel',
    'Sao Jose dos Pinhais',
    'Foz do Iguacu',
    'Colombo',
    'Guarapuava',
    'Paranagua',
    'Araucaria',
    'Toledo',
    'Apucarana',
    'Pinhais',
    'Campo Largo',
  ],
  PE: [
    'Recife',
    'Jaboatao dos Guararapes',
    'Olinda',
    'Caruaru',
    'Petrolina',
    'Paulista',
    'Cabo de Santo Agostinho',
    'Camaragibe',
    'Garanhuns',
    'Vitoria de Santo Antao',
    'Igarassu',
    'Sao Lourenco da Mata',
    'Santa Cruz do Capibaribe',
    'Abreu e Lima',
    'Serra Talhada',
  ],
  PI: [
    'Teresina',
    'Parnaiba',
    'Picos',
    'Piripiri',
    'Floriano',
    'Campo Maior',
    'Barras',
    'Uniao',
    'Altos',
    'Jose de Freitas',
  ],
  RJ: [
    'Rio de Janeiro',
    'Sao Goncalo',
    'Duque de Caxias',
    'Nova Iguacu',
    'Niteroi',
    'Belford Roxo',
    'Campos dos Goytacazes',
    'Sao Joao de Meriti',
    'Petropolis',
    'Volta Redonda',
    'Magé',
    'Itaborai',
    'Macaé',
    'Mesquita',
    'Nova Friburgo',
    'Barra Mansa',
    'Cabo Frio',
    'Angra dos Reis',
    'Teresopolis',
    'Resende',
  ],
  RN: [
    'Natal',
    'Mossoro',
    'Parnamirim',
    'Sao Goncalo do Amarante',
    'Macaiba',
    'Ceara-Mirim',
    'Caico',
    'Acu',
    'Currais Novos',
    'Sao Jose de Mipibu',
  ],
  RS: [
    'Porto Alegre',
    'Caxias do Sul',
    'Pelotas',
    'Canoas',
    'Santa Maria',
    'Gravataí',
    'Viamao',
    'Novo Hamburgo',
    'Sao Leopoldo',
    'Rio Grande',
    'Alvorada',
    'Passo Fundo',
    'Sapucaia do Sul',
    'Uruguaiana',
    'Santa Cruz do Sul',
    'Cachoeirinha',
    'Bage',
    'Bento Goncalves',
    'Erechim',
    'Guaiba',
  ],
  RO: [
    'Porto Velho',
    'Ji-Parana',
    'Ariquemes',
    'Vilhena',
    'Cacoal',
    'Rolim de Moura',
    'Jaru',
    'Guajara-Mirim',
    'Ouro Preto do Oeste',
    'Buritis',
  ],
  RR: [
    'Boa Vista',
    'Rorainopolis',
    'Caracarai',
    'Alto Alegre',
    'Mucajai',
    'Canta',
    'Bonfim',
    'Pacaraima',
    'Normandia',
    'Iracema',
  ],
  SC: [
    'Joinville',
    'Florianopolis',
    'Blumenau',
    'Sao Jose',
    'Chapeco',
    'Criciuma',
    'Itajai',
    'Jaragua do Sul',
    'Lages',
    'Palhoca',
    'Balneario Camboriu',
    'Brusque',
    'Tubarao',
    'Sao Bento do Sul',
    'Cacador',
  ],
  SP: [
    'Sao Paulo',
    'Guarulhos',
    'Campinas',
    'Sao Bernardo do Campo',
    'Santo Andre',
    'Osasco',
    'Ribeirao Preto',
    'Sorocaba',
    'Mauá',
    'Sao Jose dos Campos',
    'Santos',
    'Mogi das Cruzes',
    'Diadema',
    'Jundiai',
    'Piracicaba',
    'Carapicuiba',
    'Bauru',
    'Itaquaquecetuba',
    'Sao Vicente',
    'Franca',
    'Praia Grande',
    'Guaruja',
    'Taubate',
    'Limeira',
    'Suzano',
    'Taboao da Serra',
    'Sumare',
    'Barueri',
    'Embu das Artes',
    'Sao Carlos',
  ],
  SE: [
    'Aracaju',
    'Nossa Senhora do Socorro',
    'Lagarto',
    'Itabaiana',
    'Sao Cristovao',
    'Estancia',
    'Tobias Barreto',
    'Itabaianinha',
    'Simao Dias',
    'Capela',
  ],
  TO: [
    'Palmas',
    'Araguaina',
    'Gurupi',
    'Porto Nacional',
    'Paraiso do Tocantins',
    'Colinas do Tocantins',
    'Guarai',
    'Tocantinopolis',
    'Dianopolis',
    'Miracema do Tocantins',
  ],
};

// Funcao helper para obter cidades de um estado
export function getCitiesByState(stateCode: string): string[] {
  return BRAZILIAN_CITIES[stateCode] || [];
}
