// Lista completa de países do mundo com configurações de endereço

export type CountryAddressConfig = {
  code: string;
  name: string;
  dial: string;
  phoneFormat: string;
  phoneLength: number;
  // Configuração de campos de endereço
  postalCodeLabel: string;
  postalCodePlaceholder: string;
  postalCodeFormat?: RegExp;
  postalCodeMaxLength?: number;
  hasAutoComplete?: boolean; // Tem API de preenchimento automático
  // Campos de endereço específicos
  addressFields: {
    line1Label: string; // Rua, Street, Road, etc.
    line2Label?: string; // Número, Apt, etc.
    neighborhoodLabel?: string; // Bairro, District, etc.
    cityLabel: string;
    stateLabel?: string; // Estado, Province, Region, etc.
    statePlaceholder?: string;
    stateMaxLength?: number;
  };
};

export const COUNTRIES: CountryAddressConfig[] = [
  // AMÉRICA DO SUL
  {
    code: 'BR',
    name: 'Brasil',
    dial: '+55',
    phoneFormat: '(##) #####-####',
    phoneLength: 11,
    postalCodeLabel: 'CEP',
    postalCodePlaceholder: '00000-000',
    postalCodeMaxLength: 8,
    hasAutoComplete: true, // ViaCEP
    addressFields: {
      line1Label: 'Rua',
      line2Label: 'Número',
      neighborhoodLabel: 'Bairro',
      cityLabel: 'Cidade',
      stateLabel: 'Estado (UF)',
      statePlaceholder: 'SP',
      stateMaxLength: 2,
    },
  },
  {
    code: 'AR',
    name: 'Argentina',
    dial: '+54',
    phoneFormat: '## ####-####',
    phoneLength: 10,
    postalCodeLabel: 'Código Postal',
    postalCodePlaceholder: 'C1000',
    postalCodeMaxLength: 8,
    addressFields: {
      line1Label: 'Calle',
      line2Label: 'Número',
      neighborhoodLabel: 'Barrio',
      cityLabel: 'Ciudad',
      stateLabel: 'Provincia',
      statePlaceholder: 'Buenos Aires',
    },
  },
  {
    code: 'CL',
    name: 'Chile',
    dial: '+56',
    phoneFormat: '# #### ####',
    phoneLength: 9,
    postalCodeLabel: 'Código Postal',
    postalCodePlaceholder: '8320000',
    postalCodeMaxLength: 7,
    addressFields: {
      line1Label: 'Calle',
      line2Label: 'Número',
      neighborhoodLabel: 'Comuna',
      cityLabel: 'Ciudad',
      stateLabel: 'Región',
    },
  },
  {
    code: 'CO',
    name: 'Colômbia',
    dial: '+57',
    phoneFormat: '### ### ####',
    phoneLength: 10,
    postalCodeLabel: 'Código Postal',
    postalCodePlaceholder: '110111',
    postalCodeMaxLength: 6,
    addressFields: {
      line1Label: 'Dirección',
      line2Label: 'Número',
      neighborhoodLabel: 'Barrio',
      cityLabel: 'Ciudad',
      stateLabel: 'Departamento',
    },
  },
  {
    code: 'UY',
    name: 'Uruguai',
    dial: '+598',
    phoneFormat: '# ### ## ##',
    phoneLength: 8,
    postalCodeLabel: 'Código Postal',
    postalCodePlaceholder: '11000',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Calle',
      line2Label: 'Número',
      cityLabel: 'Ciudad',
      stateLabel: 'Departamento',
    },
  },
  {
    code: 'PY',
    name: 'Paraguai',
    dial: '+595',
    phoneFormat: '### ### ###',
    phoneLength: 9,
    postalCodeLabel: 'Código Postal',
    postalCodePlaceholder: '1536',
    postalCodeMaxLength: 4,
    addressFields: {
      line1Label: 'Calle',
      line2Label: 'Número',
      cityLabel: 'Ciudad',
      stateLabel: 'Departamento',
    },
  },
  {
    code: 'PE',
    name: 'Peru',
    dial: '+51',
    phoneFormat: '### ### ###',
    phoneLength: 9,
    postalCodeLabel: 'Código Postal',
    postalCodePlaceholder: 'Lima 15001',
    postalCodeMaxLength: 10,
    addressFields: {
      line1Label: 'Dirección',
      line2Label: 'Número',
      neighborhoodLabel: 'Distrito',
      cityLabel: 'Ciudad',
      stateLabel: 'Departamento',
    },
  },
  {
    code: 'BO',
    name: 'Bolívia',
    dial: '+591',
    phoneFormat: '# ### ####',
    phoneLength: 8,
    postalCodeLabel: 'Código Postal',
    postalCodePlaceholder: '0000',
    postalCodeMaxLength: 4,
    addressFields: {
      line1Label: 'Calle',
      line2Label: 'Número',
      cityLabel: 'Ciudad',
      stateLabel: 'Departamento',
    },
  },
  {
    code: 'EC',
    name: 'Equador',
    dial: '+593',
    phoneFormat: '## ### ####',
    phoneLength: 9,
    postalCodeLabel: 'Código Postal',
    postalCodePlaceholder: 'EC170150',
    postalCodeMaxLength: 8,
    addressFields: {
      line1Label: 'Calle',
      line2Label: 'Número',
      cityLabel: 'Ciudad',
      stateLabel: 'Provincia',
    },
  },
  {
    code: 'VE',
    name: 'Venezuela',
    dial: '+58',
    phoneFormat: '### ### ####',
    phoneLength: 10,
    postalCodeLabel: 'Código Postal',
    postalCodePlaceholder: '1010',
    postalCodeMaxLength: 4,
    addressFields: {
      line1Label: 'Dirección',
      line2Label: 'Número',
      cityLabel: 'Ciudad',
      stateLabel: 'Estado',
    },
  },

  // AMÉRICA DO NORTE
  {
    code: 'US',
    name: 'Estados Unidos',
    dial: '+1',
    phoneFormat: '(###) ###-####',
    phoneLength: 10,
    postalCodeLabel: 'ZIP Code',
    postalCodePlaceholder: '12345',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Street Address',
      line2Label: 'Apt/Suite',
      cityLabel: 'City',
      stateLabel: 'State',
      statePlaceholder: 'CA',
      stateMaxLength: 2,
    },
  },
  {
    code: 'CA',
    name: 'Canadá',
    dial: '+1',
    phoneFormat: '(###) ###-####',
    phoneLength: 10,
    postalCodeLabel: 'Postal Code',
    postalCodePlaceholder: 'A1A 1A1',
    postalCodeMaxLength: 7,
    addressFields: {
      line1Label: 'Street Address',
      line2Label: 'Apt/Unit',
      cityLabel: 'City',
      stateLabel: 'Province',
      statePlaceholder: 'ON',
      stateMaxLength: 2,
    },
  },
  {
    code: 'MX',
    name: 'México',
    dial: '+52',
    phoneFormat: '## #### ####',
    phoneLength: 10,
    postalCodeLabel: 'Código Postal',
    postalCodePlaceholder: '01000',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Calle',
      line2Label: 'Número',
      neighborhoodLabel: 'Colonia',
      cityLabel: 'Ciudad',
      stateLabel: 'Estado',
    },
  },

  // AMÉRICA CENTRAL E CARIBE
  {
    code: 'GT',
    name: 'Guatemala',
    dial: '+502',
    phoneFormat: '#### ####',
    phoneLength: 8,
    postalCodeLabel: 'Código Postal',
    postalCodePlaceholder: '01001',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Dirección',
      line2Label: 'Número',
      cityLabel: 'Ciudad',
      stateLabel: 'Departamento',
    },
  },
  {
    code: 'CR',
    name: 'Costa Rica',
    dial: '+506',
    phoneFormat: '#### ####',
    phoneLength: 8,
    postalCodeLabel: 'Código Postal',
    postalCodePlaceholder: '10101',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Dirección',
      line2Label: 'Número',
      cityLabel: 'Ciudad',
      stateLabel: 'Provincia',
    },
  },
  {
    code: 'PA',
    name: 'Panamá',
    dial: '+507',
    phoneFormat: '#### ####',
    phoneLength: 8,
    postalCodeLabel: 'Código Postal',
    postalCodePlaceholder: '0801',
    postalCodeMaxLength: 4,
    addressFields: {
      line1Label: 'Dirección',
      line2Label: 'Número',
      cityLabel: 'Ciudad',
      stateLabel: 'Provincia',
    },
  },
  {
    code: 'CU',
    name: 'Cuba',
    dial: '+53',
    phoneFormat: '# ### ####',
    phoneLength: 8,
    postalCodeLabel: 'Código Postal',
    postalCodePlaceholder: '10100',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Dirección',
      line2Label: 'Número',
      cityLabel: 'Ciudad',
      stateLabel: 'Provincia',
    },
  },
  {
    code: 'DO',
    name: 'República Dominicana',
    dial: '+1-809',
    phoneFormat: '(###) ###-####',
    phoneLength: 10,
    postalCodeLabel: 'Código Postal',
    postalCodePlaceholder: '10101',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Calle',
      line2Label: 'Número',
      cityLabel: 'Ciudad',
      stateLabel: 'Provincia',
    },
  },

  // EUROPA OCIDENTAL
  {
    code: 'PT',
    name: 'Portugal',
    dial: '+351',
    phoneFormat: '### ### ###',
    phoneLength: 9,
    postalCodeLabel: 'Código Postal',
    postalCodePlaceholder: '1000-001',
    postalCodeMaxLength: 8,
    addressFields: {
      line1Label: 'Rua',
      line2Label: 'Número',
      neighborhoodLabel: 'Freguesia',
      cityLabel: 'Cidade',
      stateLabel: 'Distrito',
    },
  },
  {
    code: 'ES',
    name: 'Espanha',
    dial: '+34',
    phoneFormat: '### ## ## ##',
    phoneLength: 9,
    postalCodeLabel: 'Código Postal',
    postalCodePlaceholder: '28001',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Calle',
      line2Label: 'Número',
      cityLabel: 'Ciudad',
      stateLabel: 'Provincia',
    },
  },
  {
    code: 'FR',
    name: 'França',
    dial: '+33',
    phoneFormat: '# ## ## ## ##',
    phoneLength: 9,
    postalCodeLabel: 'Code Postal',
    postalCodePlaceholder: '75001',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Rue',
      line2Label: 'Numéro',
      cityLabel: 'Ville',
      stateLabel: 'Région',
    },
  },
  {
    code: 'IT',
    name: 'Itália',
    dial: '+39',
    phoneFormat: '### ### ####',
    phoneLength: 10,
    postalCodeLabel: 'CAP',
    postalCodePlaceholder: '00100',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Via',
      line2Label: 'Numero',
      cityLabel: 'Città',
      stateLabel: 'Provincia',
      statePlaceholder: 'RM',
      stateMaxLength: 2,
    },
  },
  {
    code: 'DE',
    name: 'Alemanha',
    dial: '+49',
    phoneFormat: '### ########',
    phoneLength: 11,
    postalCodeLabel: 'Postleitzahl',
    postalCodePlaceholder: '10115',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Straße',
      line2Label: 'Hausnummer',
      cityLabel: 'Stadt',
      stateLabel: 'Bundesland',
    },
  },
  {
    code: 'GB',
    name: 'Reino Unido',
    dial: '+44',
    phoneFormat: '#### ######',
    phoneLength: 10,
    postalCodeLabel: 'Postcode',
    postalCodePlaceholder: 'SW1A 1AA',
    postalCodeMaxLength: 8,
    addressFields: {
      line1Label: 'Street',
      line2Label: 'Number',
      cityLabel: 'City',
      stateLabel: 'County',
    },
  },
  {
    code: 'IE',
    name: 'Irlanda',
    dial: '+353',
    phoneFormat: '## ### ####',
    phoneLength: 9,
    postalCodeLabel: 'Eircode',
    postalCodePlaceholder: 'D01 F5P2',
    postalCodeMaxLength: 8,
    addressFields: {
      line1Label: 'Street',
      line2Label: 'Number',
      cityLabel: 'City',
      stateLabel: 'County',
    },
  },
  {
    code: 'NL',
    name: 'Holanda',
    dial: '+31',
    phoneFormat: '## #### ####',
    phoneLength: 10,
    postalCodeLabel: 'Postcode',
    postalCodePlaceholder: '1012 AB',
    postalCodeMaxLength: 7,
    addressFields: {
      line1Label: 'Straat',
      line2Label: 'Huisnummer',
      cityLabel: 'Stad',
      stateLabel: 'Provincie',
    },
  },
  {
    code: 'BE',
    name: 'Bélgica',
    dial: '+32',
    phoneFormat: '### ## ## ##',
    phoneLength: 9,
    postalCodeLabel: 'Code Postal',
    postalCodePlaceholder: '1000',
    postalCodeMaxLength: 4,
    addressFields: {
      line1Label: 'Rue',
      line2Label: 'Numéro',
      cityLabel: 'Ville',
      stateLabel: 'Province',
    },
  },
  {
    code: 'CH',
    name: 'Suíça',
    dial: '+41',
    phoneFormat: '## ### ## ##',
    phoneLength: 9,
    postalCodeLabel: 'PLZ',
    postalCodePlaceholder: '8001',
    postalCodeMaxLength: 4,
    addressFields: {
      line1Label: 'Strasse',
      line2Label: 'Nummer',
      cityLabel: 'Stadt',
      stateLabel: 'Kanton',
      statePlaceholder: 'ZH',
      stateMaxLength: 2,
    },
  },
  {
    code: 'AT',
    name: 'Áustria',
    dial: '+43',
    phoneFormat: '### ######',
    phoneLength: 10,
    postalCodeLabel: 'Postleitzahl',
    postalCodePlaceholder: '1010',
    postalCodeMaxLength: 4,
    addressFields: {
      line1Label: 'Straße',
      line2Label: 'Hausnummer',
      cityLabel: 'Stadt',
      stateLabel: 'Bundesland',
    },
  },

  // EUROPA DO NORTE
  {
    code: 'SE',
    name: 'Suécia',
    dial: '+46',
    phoneFormat: '## ### ## ##',
    phoneLength: 9,
    postalCodeLabel: 'Postnummer',
    postalCodePlaceholder: '123 45',
    postalCodeMaxLength: 6,
    addressFields: {
      line1Label: 'Gata',
      line2Label: 'Nummer',
      cityLabel: 'Stad',
      stateLabel: 'Län',
    },
  },
  {
    code: 'NO',
    name: 'Noruega',
    dial: '+47',
    phoneFormat: '### ## ###',
    phoneLength: 8,
    postalCodeLabel: 'Postnummer',
    postalCodePlaceholder: '0001',
    postalCodeMaxLength: 4,
    addressFields: {
      line1Label: 'Gate',
      line2Label: 'Nummer',
      cityLabel: 'By',
      stateLabel: 'Fylke',
    },
  },
  {
    code: 'DK',
    name: 'Dinamarca',
    dial: '+45',
    phoneFormat: '## ## ## ##',
    phoneLength: 8,
    postalCodeLabel: 'Postnummer',
    postalCodePlaceholder: '1050',
    postalCodeMaxLength: 4,
    addressFields: {
      line1Label: 'Vej',
      line2Label: 'Nummer',
      cityLabel: 'By',
    },
  },
  {
    code: 'FI',
    name: 'Finlândia',
    dial: '+358',
    phoneFormat: '## ### ####',
    phoneLength: 9,
    postalCodeLabel: 'Postinumero',
    postalCodePlaceholder: '00100',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Katu',
      line2Label: 'Numero',
      cityLabel: 'Kaupunki',
    },
  },
  {
    code: 'IS',
    name: 'Islândia',
    dial: '+354',
    phoneFormat: '### ####',
    phoneLength: 7,
    postalCodeLabel: 'Póstnúmer',
    postalCodePlaceholder: '101',
    postalCodeMaxLength: 3,
    addressFields: {
      line1Label: 'Gata',
      line2Label: 'Númer',
      cityLabel: 'Borg',
    },
  },

  // EUROPA DO LESTE
  {
    code: 'PL',
    name: 'Polônia',
    dial: '+48',
    phoneFormat: '### ### ###',
    phoneLength: 9,
    postalCodeLabel: 'Kod pocztowy',
    postalCodePlaceholder: '00-001',
    postalCodeMaxLength: 6,
    addressFields: {
      line1Label: 'Ulica',
      line2Label: 'Numer',
      cityLabel: 'Miasto',
      stateLabel: 'Województwo',
    },
  },
  {
    code: 'CZ',
    name: 'República Tcheca',
    dial: '+420',
    phoneFormat: '### ### ###',
    phoneLength: 9,
    postalCodeLabel: 'PSČ',
    postalCodePlaceholder: '110 00',
    postalCodeMaxLength: 6,
    addressFields: {
      line1Label: 'Ulice',
      line2Label: 'Číslo',
      cityLabel: 'Město',
    },
  },
  {
    code: 'HU',
    name: 'Hungria',
    dial: '+36',
    phoneFormat: '## ### ####',
    phoneLength: 9,
    postalCodeLabel: 'Irányítószám',
    postalCodePlaceholder: '1011',
    postalCodeMaxLength: 4,
    addressFields: {
      line1Label: 'Utca',
      line2Label: 'Házszám',
      cityLabel: 'Város',
    },
  },
  {
    code: 'RO',
    name: 'Romênia',
    dial: '+40',
    phoneFormat: '### ### ###',
    phoneLength: 9,
    postalCodeLabel: 'Cod poștal',
    postalCodePlaceholder: '010011',
    postalCodeMaxLength: 6,
    addressFields: {
      line1Label: 'Strada',
      line2Label: 'Număr',
      cityLabel: 'Oraș',
      stateLabel: 'Județ',
    },
  },
  {
    code: 'RU',
    name: 'Rússia',
    dial: '+7',
    phoneFormat: '### ###-##-##',
    phoneLength: 10,
    postalCodeLabel: 'Почтовый индекс',
    postalCodePlaceholder: '101000',
    postalCodeMaxLength: 6,
    addressFields: {
      line1Label: 'Улица',
      line2Label: 'Дом',
      cityLabel: 'Город',
      stateLabel: 'Область',
    },
  },
  {
    code: 'UA',
    name: 'Ucrânia',
    dial: '+380',
    phoneFormat: '## ### ## ##',
    phoneLength: 9,
    postalCodeLabel: 'Поштовий індекс',
    postalCodePlaceholder: '01001',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Вулиця',
      line2Label: 'Будинок',
      cityLabel: 'Місто',
      stateLabel: 'Область',
    },
  },

  // ÁSIA
  {
    code: 'JP',
    name: 'Japão',
    dial: '+81',
    phoneFormat: '## #### ####',
    phoneLength: 10,
    postalCodeLabel: '郵便番号',
    postalCodePlaceholder: '100-0001',
    postalCodeMaxLength: 8,
    addressFields: {
      line1Label: '住所',
      line2Label: '番地',
      cityLabel: '市区町村',
      stateLabel: '都道府県',
    },
  },
  {
    code: 'CN',
    name: 'China',
    dial: '+86',
    phoneFormat: '### #### ####',
    phoneLength: 11,
    postalCodeLabel: '邮政编码',
    postalCodePlaceholder: '100000',
    postalCodeMaxLength: 6,
    addressFields: {
      line1Label: '街道',
      line2Label: '门牌号',
      cityLabel: '城市',
      stateLabel: '省/直辖市',
    },
  },
  {
    code: 'KR',
    name: 'Coreia do Sul',
    dial: '+82',
    phoneFormat: '## #### ####',
    phoneLength: 10,
    postalCodeLabel: '우편번호',
    postalCodePlaceholder: '06001',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: '도로명',
      line2Label: '번지',
      cityLabel: '시/군/구',
      stateLabel: '시/도',
    },
  },
  {
    code: 'IN',
    name: 'Índia',
    dial: '+91',
    phoneFormat: '##### #####',
    phoneLength: 10,
    postalCodeLabel: 'PIN Code',
    postalCodePlaceholder: '110001',
    postalCodeMaxLength: 6,
    addressFields: {
      line1Label: 'Street',
      line2Label: 'Number',
      cityLabel: 'City',
      stateLabel: 'State',
    },
  },
  {
    code: 'TH',
    name: 'Tailândia',
    dial: '+66',
    phoneFormat: '## ### ####',
    phoneLength: 9,
    postalCodeLabel: 'รหัสไปรษณีย์',
    postalCodePlaceholder: '10100',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'ถนน',
      line2Label: 'บ้านเลขที่',
      cityLabel: 'อำเภอ',
      stateLabel: 'จังหวัด',
    },
  },
  {
    code: 'VN',
    name: 'Vietnã',
    dial: '+84',
    phoneFormat: '### ### ####',
    phoneLength: 10,
    postalCodeLabel: 'Mã bưu điện',
    postalCodePlaceholder: '100000',
    postalCodeMaxLength: 6,
    addressFields: {
      line1Label: 'Đường',
      line2Label: 'Số nhà',
      cityLabel: 'Thành phố',
      stateLabel: 'Tỉnh',
    },
  },
  {
    code: 'ID',
    name: 'Indonésia',
    dial: '+62',
    phoneFormat: '### #### ####',
    phoneLength: 11,
    postalCodeLabel: 'Kode Pos',
    postalCodePlaceholder: '10110',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Jalan',
      line2Label: 'Nomor',
      cityLabel: 'Kota',
      stateLabel: 'Provinsi',
    },
  },
  {
    code: 'MY',
    name: 'Malásia',
    dial: '+60',
    phoneFormat: '## ### ####',
    phoneLength: 10,
    postalCodeLabel: 'Postcode',
    postalCodePlaceholder: '50000',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Jalan',
      line2Label: 'Nombor',
      cityLabel: 'Bandar',
      stateLabel: 'Negeri',
    },
  },
  {
    code: 'SG',
    name: 'Singapura',
    dial: '+65',
    phoneFormat: '#### ####',
    phoneLength: 8,
    postalCodeLabel: 'Postal Code',
    postalCodePlaceholder: '018956',
    postalCodeMaxLength: 6,
    addressFields: {
      line1Label: 'Street',
      line2Label: 'Unit',
      cityLabel: 'District',
    },
  },
  {
    code: 'PH',
    name: 'Filipinas',
    dial: '+63',
    phoneFormat: '### ### ####',
    phoneLength: 10,
    postalCodeLabel: 'ZIP Code',
    postalCodePlaceholder: '1000',
    postalCodeMaxLength: 4,
    addressFields: {
      line1Label: 'Street',
      line2Label: 'Number',
      cityLabel: 'City',
      stateLabel: 'Province',
    },
  },
  {
    code: 'PK',
    name: 'Paquistão',
    dial: '+92',
    phoneFormat: '### #######',
    phoneLength: 10,
    postalCodeLabel: 'Postal Code',
    postalCodePlaceholder: '44000',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Street',
      line2Label: 'Number',
      cityLabel: 'City',
      stateLabel: 'Province',
    },
  },

  // OCEANIA
  {
    code: 'AU',
    name: 'Austrália',
    dial: '+61',
    phoneFormat: '### ### ###',
    phoneLength: 9,
    postalCodeLabel: 'Postcode',
    postalCodePlaceholder: '2000',
    postalCodeMaxLength: 4,
    addressFields: {
      line1Label: 'Street',
      line2Label: 'Number',
      cityLabel: 'Suburb',
      stateLabel: 'State',
      statePlaceholder: 'NSW',
      stateMaxLength: 3,
    },
  },
  {
    code: 'NZ',
    name: 'Nova Zelândia',
    dial: '+64',
    phoneFormat: '## ### ####',
    phoneLength: 9,
    postalCodeLabel: 'Postcode',
    postalCodePlaceholder: '1010',
    postalCodeMaxLength: 4,
    addressFields: {
      line1Label: 'Street',
      line2Label: 'Number',
      cityLabel: 'Suburb',
      stateLabel: 'Region',
    },
  },

  // ÁFRICA
  {
    code: 'ZA',
    name: 'África do Sul',
    dial: '+27',
    phoneFormat: '## ### ####',
    phoneLength: 9,
    postalCodeLabel: 'Postal Code',
    postalCodePlaceholder: '0001',
    postalCodeMaxLength: 4,
    addressFields: {
      line1Label: 'Street',
      line2Label: 'Number',
      cityLabel: 'City',
      stateLabel: 'Province',
    },
  },
  {
    code: 'EG',
    name: 'Egito',
    dial: '+20',
    phoneFormat: '## #### ####',
    phoneLength: 10,
    postalCodeLabel: 'Postal Code',
    postalCodePlaceholder: '11511',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Street',
      line2Label: 'Number',
      cityLabel: 'City',
      stateLabel: 'Governorate',
    },
  },
  {
    code: 'NG',
    name: 'Nigéria',
    dial: '+234',
    phoneFormat: '### ### ####',
    phoneLength: 10,
    postalCodeLabel: 'Postal Code',
    postalCodePlaceholder: '100001',
    postalCodeMaxLength: 6,
    addressFields: {
      line1Label: 'Street',
      line2Label: 'Number',
      cityLabel: 'City',
      stateLabel: 'State',
    },
  },
  {
    code: 'KE',
    name: 'Quênia',
    dial: '+254',
    phoneFormat: '### ######',
    phoneLength: 9,
    postalCodeLabel: 'Postal Code',
    postalCodePlaceholder: '00100',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Street',
      line2Label: 'Number',
      cityLabel: 'City',
      stateLabel: 'County',
    },
  },
  {
    code: 'MA',
    name: 'Marrocos',
    dial: '+212',
    phoneFormat: '### ######',
    phoneLength: 9,
    postalCodeLabel: 'Code Postal',
    postalCodePlaceholder: '10000',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Rue',
      line2Label: 'Numéro',
      cityLabel: 'Ville',
    },
  },

  // ORIENTE MÉDIO
  {
    code: 'AE',
    name: 'Emirados Árabes Unidos',
    dial: '+971',
    phoneFormat: '## ### ####',
    phoneLength: 9,
    postalCodeLabel: 'Postal Code',
    postalCodePlaceholder: '00000',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Street',
      line2Label: 'Number',
      cityLabel: 'Emirate',
    },
  },
  {
    code: 'SA',
    name: 'Arábia Saudita',
    dial: '+966',
    phoneFormat: '## ### ####',
    phoneLength: 9,
    postalCodeLabel: 'Postal Code',
    postalCodePlaceholder: '11564',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Street',
      line2Label: 'Number',
      cityLabel: 'City',
      stateLabel: 'Province',
    },
  },
  {
    code: 'IL',
    name: 'Israel',
    dial: '+972',
    phoneFormat: '## ### ####',
    phoneLength: 9,
    postalCodeLabel: 'Postal Code',
    postalCodePlaceholder: '6100001',
    postalCodeMaxLength: 7,
    addressFields: {
      line1Label: 'Street',
      line2Label: 'Number',
      cityLabel: 'City',
    },
  },
  {
    code: 'TR',
    name: 'Turquia',
    dial: '+90',
    phoneFormat: '### ### ## ##',
    phoneLength: 10,
    postalCodeLabel: 'Posta Kodu',
    postalCodePlaceholder: '34000',
    postalCodeMaxLength: 5,
    addressFields: {
      line1Label: 'Sokak',
      line2Label: 'Numara',
      cityLabel: 'İl',
      stateLabel: 'İlçe',
    },
  },
];

// Criar um mapa para busca rápida por código
export const COUNTRIES_MAP = COUNTRIES.reduce(
  (acc, country) => {
    acc[country.code] = country;
    return acc;
  },
  {} as Record<string, CountryAddressConfig>,
);

// Função para obter configuração de país
export const getCountryConfig = (
  code: string,
): CountryAddressConfig | undefined => {
  return COUNTRIES_MAP[code];
};
