// Lista de cidades portuguesas por distrito para dropdown

export const PORTUGAL_DISTRICTS = [
  { code: 'AV', name: 'Aveiro' },
  { code: 'BE', name: 'Beja' },
  { code: 'BR', name: 'Braga' },
  { code: 'BG', name: 'Braganca' },
  { code: 'CB', name: 'Castelo Branco' },
  { code: 'CO', name: 'Coimbra' },
  { code: 'EV', name: 'Evora' },
  { code: 'FA', name: 'Faro' },
  { code: 'GU', name: 'Guarda' },
  { code: 'LE', name: 'Leiria' },
  { code: 'LI', name: 'Lisboa' },
  { code: 'PO', name: 'Portalegre' },
  { code: 'PT', name: 'Porto' },
  { code: 'SA', name: 'Santarem' },
  { code: 'SE', name: 'Setubal' },
  { code: 'VC', name: 'Viana do Castelo' },
  { code: 'VR', name: 'Vila Real' },
  { code: 'VS', name: 'Viseu' },
  { code: 'RA', name: 'Regiao Autonoma dos Acores' },
  { code: 'RM', name: 'Regiao Autonoma da Madeira' },
] as const;

export type PortugalDistrictCode = (typeof PORTUGAL_DISTRICTS)[number]['code'];

export const PORTUGAL_CITIES: Record<string, string[]> = {
  AV: [
    'Aveiro',
    'Ilhavo',
    'Ovar',
    'Santa Maria da Feira',
    'Oliveira de Azemeis',
    'Sao Joao da Madeira',
    'Agueda',
    'Estarreja',
    'Vagos',
    'Espinho',
  ],
  BE: [
    'Beja',
    'Moura',
    'Serpa',
    'Castro Verde',
    'Mertola',
    'Odemira',
    'Aljustrel',
    'Ferreira do Alentejo',
    'Ourique',
    'Vidigueira',
  ],
  BR: [
    'Braga',
    'Guimaraes',
    'Vila Nova de Famalicao',
    'Barcelos',
    'Fafe',
    'Vila Verde',
    'Esposende',
    'Amares',
    'Povoa de Lanhoso',
    'Vizela',
  ],
  BG: [
    'Braganca',
    'Mirandela',
    'Macedo de Cavaleiros',
    'Miranda do Douro',
    'Mogadouro',
    'Carrazeda de Ansiaes',
    'Torre de Moncorvo',
    'Vila Flor',
    'Alfandega da Fe',
    'Freixo de Espada a Cinta',
  ],
  CB: [
    'Castelo Branco',
    'Covilha',
    'Fundao',
    'Idanha-a-Nova',
    'Penamacor',
    'Proenca-a-Nova',
    'Serta',
    'Oleiros',
    'Vila de Rei',
    'Vila Velha de Rodao',
  ],
  CO: [
    'Coimbra',
    'Figueira da Foz',
    'Cantanhede',
    'Montemor-o-Velho',
    'Condeixa-a-Nova',
    'Mira',
    'Penacova',
    'Lousa',
    'Soure',
    'Mealhada',
  ],
  EV: [
    'Evora',
    'Estremoz',
    'Reguengos de Monsaraz',
    'Montemor-o-Novo',
    'Vendas Novas',
    'Borba',
    'Arraiolos',
    'Vila Vicosa',
    'Mora',
    'Redondo',
  ],
  FA: [
    'Faro',
    'Portimao',
    'Loule',
    'Albufeira',
    'Olhao',
    'Silves',
    'Lagos',
    'Tavira',
    'Vila Real de Santo Antonio',
    'Lagoa',
  ],
  GU: [
    'Guarda',
    'Seia',
    'Gouveia',
    'Sabugal',
    'Pinhel',
    'Almeida',
    'Trancoso',
    'Celorico da Beira',
    'Figueira de Castelo Rodrigo',
    'Meda',
  ],
  LE: [
    'Leiria',
    'Caldas da Rainha',
    'Marinha Grande',
    'Pombal',
    'Peniche',
    'Alcobaca',
    'Obidos',
    'Nazare',
    'Batalha',
    'Porto de Mos',
  ],
  LI: [
    'Lisboa',
    'Sintra',
    'Cascais',
    'Loures',
    'Almada',
    'Amadora',
    'Oeiras',
    'Odivelas',
    'Vila Franca de Xira',
    'Mafra',
    'Queluz',
    'Agualva-Cacem',
    'Benfica',
    'Lumiar',
    'Olivais',
  ],
  PO: [
    'Portalegre',
    'Elvas',
    'Ponte de Sor',
    'Campo Maior',
    'Nisa',
    'Marvao',
    'Castelo de Vide',
    'Crato',
    'Arronches',
    'Avis',
  ],
  PT: [
    'Porto',
    'Vila Nova de Gaia',
    'Matosinhos',
    'Maia',
    'Gondomar',
    'Valongo',
    'Paredes',
    'Penafiel',
    'Vila do Conde',
    'Povoa de Varzim',
    'Santo Tirso',
    'Trofa',
    'Amarante',
    'Marco de Canaveses',
    'Lousada',
  ],
  SA: [
    'Santarem',
    'Torres Novas',
    'Tomar',
    'Abrantes',
    'Entroncamento',
    'Ourem',
    'Rio Maior',
    'Cartaxo',
    'Almeirim',
    'Benavente',
  ],
  SE: [
    'Setubal',
    'Almada',
    'Seixal',
    'Barreiro',
    'Moita',
    'Montijo',
    'Sesimbra',
    'Palmela',
    'Santiago do Cacem',
    'Alcacer do Sal',
  ],
  VC: [
    'Viana do Castelo',
    'Ponte de Lima',
    'Arcos de Valdevez',
    'Caminha',
    'Monacao',
    'Valenca',
    'Paredes de Coura',
    'Vila Nova de Cerveira',
    'Melgaco',
    'Ponte da Barca',
  ],
  VR: [
    'Vila Real',
    'Chaves',
    'Peso da Regua',
    'Mondim de Basto',
    'Ribeira de Pena',
    'Sabrosa',
    'Santa Marta de Penaguiao',
    'Vila Pouca de Aguiar',
    'Alijo',
    'Boticas',
  ],
  VS: [
    'Viseu',
    'Lamego',
    'Tondela',
    'Mangualde',
    'Nelas',
    'Santa Comba Dao',
    'Sao Pedro do Sul',
    'Vouzela',
    'Oliveira de Frades',
    'Castro Daire',
  ],
  RA: [
    'Ponta Delgada',
    'Angra do Heroismo',
    'Horta',
    'Ribeira Grande',
    'Lagoa',
    'Vila Franca do Campo',
    'Praia da Vitoria',
    'Vila do Porto',
    'Nordeste',
    'Povoacao',
  ],
  RM: [
    'Funchal',
    'Camara de Lobos',
    'Machico',
    'Santa Cruz',
    'Santana',
    'Calheta',
    'Ponta do Sol',
    'Ribeira Brava',
    'Sao Vicente',
    'Porto Santo',
  ],
};

export function getCitiesByDistrict(districtCode: string): string[] {
  return PORTUGAL_CITIES[districtCode] || [];
}
